#!/usr/bin/env python3
"""Generate the ADC_BLOCK offset-MC pilot netlists and `klt sim` requests.

Deterministic: same arguments -> byte-identical output. See
sim/adc-offset-mc/README.md for the estimator this implements and why.

    python3 sim/adc-offset-mc/testbench/gen_pilot.py            # writes beside this file
    python3 sim/adc-offset-mc/testbench/gen_pilot.py --check    # fail if committed files differ

Screening stage (issue #454): also emits the 45 per-corner requests (request_screen_<point>.json, beside the netlist)
(`--check` covers them and the unique seed schedule); never run by this script.

Nothing here invents a `klt sim` field: the request uses the documented
`monte_carlo` object {n, seed, vary} of the pinned klt (see README.md).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ---- the declared measurement design (README.md section 3) ------------------
T_CYC = 200e-9          # one DR-0014 sample/redistribute/decide cycle
STEP_V = 0.5e-3         # differential input step between conversions = resolution
N_STEPS = 33            # conversions per Monte Carlo sample
D_START_V = -4.0e-3     # first differential input (V_inp - V_inn); nominal null threshold probed at +3.25 mV
VCM = 1.65              # nominal V_dd/2 at the single pilot corner
VDD = 3.3
MC_N = 8                # pilot draws (NOT a campaign size)
MC_SEED = 20261009      # base seed; klt derives per-sample seeds from it
NULL_N = 4
ENABLED_NETLIST = "tb_adc_offset_mc.spice"
NULL_NETLIST = "tb_adc_offset_null.spice"
EXTRACTED = "../../adc-block-pex/netlist-snapshots/20261008-185501-c618a90d.spice"

TT = ["typical", "res_typical", "bjt_typical", "diode_typical", "moscap_typical", "mimcap_typical"]


def ns(t: float) -> str:
    return f"{t * 1e9:.4f}n"


def pwl(points):
    out, line = [], "pwl("
    parts = [f"{ns(t)} {v:g}" for t, v in points]
    return "pwl(" + " ".join(parts) + ")"


def wrap(prefix: str, body: str, width=100) -> list[str]:
    toks, lines, cur = body.split(" "), [], prefix
    for t in toks:
        if len(cur) + len(t) + 1 > width:
            lines.append(cur)
            cur = "+ " + t
        else:
            cur += (" " if not cur.endswith(" ") and cur != prefix else "") + t if cur != prefix else t
    lines.append(cur)
    return lines


def diffs():
    return [D_START_V + k * STEP_V for k in range(N_STEPS)]


def control_pwls(n_steps: int = N_STEPS):
    """0/1 logic PWLs for tp (top-plate reset), sel (input legs), rel (to V_cm), clk."""
    e = 0.2e-9
    tp, sel, rel, clk = [(0.0, 1)], [(0.0, 1)], [(0.0, 0)], [(0.0, 0)]
    for k in range(n_steps):
        t0 = k * T_CYC
        # tp: high through acquisition, falls at 100 ns (THE sampling instant)
        tp += [(t0 + 100e-9, 1), (t0 + 100e-9 + e, 0), (t0 + 185e-9, 0), (t0 + 185e-9 + e, 1)]
        sel += [(t0 + 110e-9, 1), (t0 + 110e-9 + e, 0), (t0 + 188e-9, 0), (t0 + 188e-9 + e, 1)]
        rel += [(t0 + 115e-9, 0), (t0 + 115e-9 + e, 1), (t0 + 182e-9, 1), (t0 + 182e-9 + e, 0)]
        clk += [(t0 + 150e-9, 0), (t0 + 150.1e-9, 1), (t0 + 180e-9, 1), (t0 + 180.1e-9, 0)]
    return tp, sel, rel, clk


def input_pwls(seq=None, base: float = VCM):
    """Differential-input PWLs for the staircase `seq` (default: the pilot's ascending one).
    `base` is the common mode added to +/- d/2 (pilot: absolute VCM; screening: 0, the
    source is stacked on the `vcm` node so it follows the per-corner supply)."""
    seq = diffs() if seq is None else seq
    pp, pn = [(0.0, base + seq[0] / 2)], [(0.0, base - seq[0] / 2)]
    prev = seq[0]
    for k, d in enumerate(seq):
        if k == 0:
            continue
        t = k * T_CYC - 8e-9          # input moves while the input legs are on
        pp += [(t, base + prev / 2), (t + 0.2e-9, base + d / 2)]
        pn += [(t, base - prev / 2), (t + 0.2e-9, base - d / 2)]
        prev = d
    return pp, pn


def read_times(n_steps: int = N_STEPS):
    return [k * T_CYC + 178e-9 for k in range(n_steps)]


def netlist(mismatch: bool, screen: bool = False) -> str:
    sw = 1 if mismatch else 0
    seq = screen_seq() if screen else diffs()
    tp, sel, rel, clk = control_pwls(len(seq))
    pp, pn = input_pwls(seq, 0.0 if screen else VCM)
    name = ("tb_adc_offset_screen" if mismatch else "tb_adc_offset_screen_null") if screen else (
        "tb_adc_offset_mc" if mismatch else "tb_adc_offset_null")
    L = [
        f"* {name} -- GENERATED by gen_pilot.py, do not edit.",
        "* Comparator-inclusive ADC_BLOCK input-offset measurement, issue %s." % ("#454 (screening, up+down staircase)" if screen else "#427"),
        "* One transient = one mismatch draw = %d back-to-back DR-0014 conversions of a" % len(seq),
        "* differential-input staircase (%.1f mV start, %.2f mV step%s). See sim/adc-offset-mc/README.md." % (
            seq[0] * 1e3, STEP_V * 1e3, "; ascending then descending, section 6.6" if screen else ""),
        "*",
        "* Mismatch switch: sw_stat_mismatch=%d (%s). sw_stat_global=0 in both, so the" % (sw, "ON: per-instance MOS mismatch" if mismatch else "OFF: null control"),
        "* population is mismatch-only (no global process spread).",
        f'.include "{EXTRACTED}"',
        "",
        f".param sw_stat_global=0 sw_stat_mismatch={sw} mc_skew=3 res_mc_skew=3",
        "+ cap_mc_skew=3 fnoicor=0",
        "",
        f"Vdd   vdd  0 dc {VDD}",
        f"Vref  vref 0 dc {VDD}",
        f"Vcm   vcm  0 dc {VCM}",
        "* parasitic caps in the extracted deck reference the global substrate net `vsubs`;",
        "* tied to ground (the bodies are already tied inside the extracted netlist, DR-0035).",
        "Vsubs vsubs 0 dc 0",
        "Ibias vdd  ibias dc 10u",
        "",
    ]
    if screen:
        L += ["* inputs are stacked on the vcm node, so V_cm (and the +/-d/2 about it) follow the",
              "* per-corner supply_v override of Vcm; the differential stimulus is supply-independent."]
        L += wrap("Vinp  pinp vcm ", pwl(pp))
        L += wrap("Vinn  pinn vcm ", pwl(pn))
    else:
        L += wrap("Vinp  pinp 0 ", pwl(pp))
        L += wrap("Vinn  pinn 0 ", pwl(pn))
    L += wrap("Vtpl   tp_l   0 ", pwl(tp))
    L += wrap("Vsell  sel_l  0 ", pwl(sel))
    L += wrap("Vrell  rel_l  0 ", pwl(rel))
    L += wrap("Vclkl  clk_l  0 ", pwl(clk))
    L += [
        "Btp    tp_gn  0 v = v(vdd)*v(tp_l)",
        "Bsel   sel_in 0 v = v(vdd)*v(sel_l)",
        "Brel   relall 0 v = v(vdd)*v(rel_l)",
        "Bclk   cmpclk 0 v = v(vdd)*v(clk_l)",
        "",
        "Xdut cmpclk dout doutb",
        "+ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
        "+ ibias",
        "+ 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0",
        "+ pinn pinp",
        "+ relall relall relall relall relall relall relall relall relall",
        "+ relall relall relall relall relall relall relall relall relall",
        "+ sel_in topn topp tp_gn vcm vdd vref 0",
        "+ ADC_BLOCK",
        "",
    ]
    return "\n".join(L)


def request(netlist_name: str, mismatch_on: bool, warn: bool = False) -> dict:
    n = MC_N if mismatch_on else NULL_N
    meas = [
        {"name": f"d{k:02d}", "spice": f".meas tran d{k:02d} FIND v(dout) AT={ns(t)}", "unit": "V"}
        for k, t in enumerate(read_times())
    ]
    req = {
        "_comment": [
            "Pilot request, issue #427. %s: sw_stat_mismatch=%d in the netlist." % (netlist_name, 1 if mismatch_on else 0),
            "monte_carlo is klt sim's native object {n, seed, vary}; vary='mismatch' draws a",
            "fresh per-sample `.options seed=` (klt derives it from `seed`), process held at the",
            "single corner. n=%d is a QUALIFICATION pilot, not a campaign size." % n,
            "d00..d%02d are the dout levels of the %d conversions at differential inputs" % (N_STEPS - 1, N_STEPS),
            "D_START + k*STEP (see gen_pilot.py); analyze_pilot.py turns them into a threshold.",
        ],
        "netlist": netlist_name,
        "engine": "ngspice",
        "models": {"pdk": "gf180mcuD", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": "tt", "sections": TT}],
            "supply_v": {},
            "temperature_c": [27],
        },
        "monte_carlo": {"n": n, "seed": MC_SEED, "vary": "mismatch"},
        "analysis": {"kind": "tran", "args": f"100p {ns(N_STEPS * T_CYC)[:-1]}n 0 100p"},
        "measurements": meas,
        "options": {"keep_artifacts": True, "timeout_s": 3600, "ngspice_init": ["set numdgt=10"]},
    }
    if warn:
        req["_comment"].append(
            "batch.runner_version_check='warn' (documented klt request field): run on a fleet runner "
            "older than the client instead of refusing. The skew is stamped into the report; whether "
            "the old runner honours the per-sample seeds is exactly what the repeat/null/duplicate "
            "checks in analyze_pilot.py test."
        )
        req["batch"] = {"runner_version_check": "warn"}
    return req


# ---- screening stage (README.md section 6.3 / 6.6, issue #454) -------------
SCR_D_START_V = -6.0e-3   # widened about the pilot mean 3.69 mV: >= 3 LSB_se (9.668 mV) beyond it each side
SCR_N_UP = 41             # -6.0 .. +14.0 mV in 0.5 mV steps
SCR_N = 30                # draws per corner (section 6.3)
SCR_BASE_SEED = 20261454  # declared campaign base seed; per-corner request seeds derive from it
SCR_PROCESS = ["tt", "ff", "ss", "fs", "sf"]
SCR_VDD = [2.97, 3.3, 3.63]
SCR_TEMP_C = [-40, 27, 125]
SCREEN_NETLIST = "tb_adc_offset_screen.spice"
SCREEN_NULL_NETLIST = "tb_adc_offset_screen_null.spice"
PROCESS_SECTIONS = {
    "tt": TT,
    "ff": ["ff", "res_ff", "bjt_ff", "diode_ff", "moscap_ff", "mimcap_ff"],
    "ss": ["ss", "res_ss", "bjt_ss", "diode_ss", "moscap_ss", "mimcap_ss"],
    "fs": ["fs", "res_typical", "bjt_typical", "diode_typical", "moscap_typical", "mimcap_typical"],
    "sf": ["sf", "res_typical", "bjt_typical", "diode_typical", "moscap_typical", "mimcap_typical"],
}


def screen_up():
    return [SCR_D_START_V + k * STEP_V for k in range(SCR_N_UP)]


def screen_seq():
    """Ascending staircase then the same levels descending (the top level is read twice:
    once as the last up step, once as the first down step -- a back-to-back repeat that
    itself exercises conversion-to-conversion memory)."""
    up = screen_up()
    return up + up[::-1]


def point_name(proc: str, vdd: float, temp: int) -> str:
    return f"{proc}_v{vdd:.2f}_t{temp:+d}".replace("+", "p").replace("-", "m")


def screen_points():
    return [(p, v, t) for p in SCR_PROCESS for v in SCR_VDD for t in SCR_TEMP_C]


def point_seed(name: str, base: int = SCR_BASE_SEED) -> int:
    """Deterministic per-corner request seed: sha256(base:name) -> 31 bits. klt derives the
    per-sample seeds from the request seed, so distinct request seeds give independent
    corner populations; uniqueness across the 45 is asserted by --check and the tests."""
    import hashlib
    return int.from_bytes(hashlib.sha256(f"{base}:{name}".encode()).digest()[:4], "big") & 0x7FFFFFFF


def screen_request(proc: str, vdd: float, temp: int, netlist_name: str = SCREEN_NETLIST,
                   n: int = SCR_N, warn: bool = False) -> dict:
    name = point_name(proc, vdd, temp)
    seq = screen_seq()
    meas = []
    for k, t in enumerate(read_times(len(seq))):
        label = f"u{k:02d}" if k < SCR_N_UP else f"r{k - SCR_N_UP:02d}"
        meas.append({"name": label, "spice": f".meas tran {label} FIND v(dout) AT={ns(t)}", "unit": "V"})
    req = {
        "_comment": [
            "Screening-stage request for ONE PVT point, issue #454 (README section 6.3). Not run here.",
            "point %s: process %s, V_dd=V_ref=%.2f V, V_cm=V_dd/2, T=%d C." % (name, proc, vdd, temp),
            "monte_carlo seed = sha256('%d:%s') & 0x7fffffff (gen_pilot.point_seed); base seed %d is the" % (SCR_BASE_SEED, name, SCR_BASE_SEED),
            "declared campaign seed. n=%d draws. One request per point so the batch fleet parallelizes (6.7 item 3)." % n,
            "u00..u%02d: dout of the ascending staircase (D = %.1f mV + k*%.2f mV);" % (SCR_N_UP - 1, SCR_D_START_V * 1e3, STEP_V * 1e3),
            "r00..r%02d: dout of the descending staircase (D = %.1f mV - k*%.2f mV). hysteresis = up - down threshold." % (
                SCR_N_UP - 1, screen_up()[-1] * 1e3, STEP_V * 1e3),
        ],
        "netlist": netlist_name,
        "engine": "ngspice",
        "models": {"pdk": "gf180mcuD", "lib": "libs.tech/ngspice/sm141064.ngspice"},
        "corners": {
            "process": [{"name": proc, "sections": PROCESS_SECTIONS[proc]}],
            "supply_v": {"Vdd": [vdd], "Vref": [vdd], "Vcm": [round(vdd / 2, 4)]},
            "temperature_c": [temp],
        },
        "monte_carlo": {"n": n, "seed": point_seed(name), "vary": "mismatch"},
        "analysis": {"kind": "tran", "args": f"100p {ns(len(seq) * T_CYC)[:-1]}n 0 100p"},
        "measurements": meas,
        "options": {"keep_artifacts": True, "timeout_s": 36000, "ngspice_init": ["set numdgt=10"]},
    }
    if warn:
        req["batch"] = {"runner_version_check": "warn"}
    return req


def screen_probe_request() -> dict:
    """n=1 local single-unit probe: tt / 3.30 V / 27 C, same seed as pilot sample 0 (README 6.6 re-check)."""
    req = screen_request("tt", 3.3, 27, n=1)
    req["monte_carlo"]["seed"] = MC_SEED
    req["_comment"].append("PROBE: n=1, seed = pilot base seed %d so sample 0 reproduces pilot sample 0 (seed 1189634286)." % MC_SEED)
    return req


def screening_outputs() -> dict[str, str]:
    out = {
        SCREEN_NETLIST: netlist(True, screen=True),
        SCREEN_NULL_NETLIST: netlist(False, screen=True),
        "request_screen_probe.json": json.dumps(screen_probe_request(), indent=2) + "\n",
    }
    for p, v, t in screen_points():
        out[f"request_screen_{point_name(p, v, t)}.json"] = json.dumps(screen_request(p, v, t), indent=2) + "\n"
    return out


def check_screening_schedule() -> list[str]:
    """Problems with the 45-point schedule (empty list = fine): count, unique names, unique
    seeds across corners, none colliding with the pilot seed, n and corner grid per 6.3."""
    bad = []
    pts = screen_points()
    if len(pts) != 45:
        bad.append(f"expected 45 points, got {len(pts)}")
    seeds = {}
    for p, v, t in pts:
        r = screen_request(p, v, t)
        s = r["monte_carlo"]["seed"]
        if s in seeds:
            bad.append(f"seed {s} used by {seeds[s]} and {point_name(p, v, t)}")
        seeds[s] = point_name(p, v, t)
        if s == MC_SEED:
            bad.append(f"{point_name(p, v, t)} reuses the pilot seed")
        if r["monte_carlo"]["n"] != SCR_N:
            bad.append(f"{point_name(p, v, t)}: n != {SCR_N}")
    return bad


def probe_request() -> dict:
    """n=1 variant of the pilot request: sample 0 only, a single unit that klt keeps local."""
    req = request(ENABLED_NETLIST, True)
    req["monte_carlo"]["n"] = 1
    req["_comment"].append("n=1 single-unit local cross-host probe of sample 0 (same seed as pilot sample 0).")
    return req


def outputs() -> dict[str, str]:
    return {
        ENABLED_NETLIST: netlist(True),
        NULL_NETLIST: netlist(False),
        "request_pilot.json": json.dumps(request(ENABLED_NETLIST, True), indent=2) + "\n",
        "request_null.json": json.dumps(request(NULL_NETLIST, False), indent=2) + "\n",
        "request_probe_sample0.json": json.dumps(probe_request(), indent=2) + "\n",
        "request_pilot_warn.json": json.dumps(request(ENABLED_NETLIST, True, True), indent=2) + "\n",
        "request_null_warn.json": json.dumps(request(NULL_NETLIST, False, True), indent=2) + "\n",
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", type=Path, default=HERE)
    args = ap.parse_args(argv)
    bad = 0
    for msg in check_screening_schedule():
        print(f"SCHEDULE: {msg}")
        bad = 1
    for name, text in {**outputs(), **screening_outputs()}.items():
        p = args.out / name
        if args.check:
            if not p.exists() or p.read_text() != text:
                print(f"DIFFERS: {p}")
                bad = 1
        else:
            p.write_text(text)
            print(f"wrote {p}")
    return bad


if __name__ == "__main__":
    sys.exit(main())
