# Timing constraint for sar_ctrl_a -- GENERATED by design/sar-logic/flow/sta_sar_ctrl.py
# (DR-0023 follow-on (c), issue #275). Regenerated in place on every run, like the
# netlist -- edit that driver, not this file.
#
# DOCUMENTATION ONLY: neither `klt place-and-route` nor `klt sta` parses a raw .sdc
# file -- both take this same constraint as inline JSON (`constraints.clock_port`/
# `.clock_period_ns`). This file restates it in SDC syntax purely for human
# readability/reproducibility, matching gf180-tmds-tx's own
# flow/tmds_encoder/sta/tmds_encoder.sdc convention. See the driver's own
# docstring ("SDC is documentation, not a tool input") for why there is no
# set_input_delay/set_output_delay/set_driving_cell/set_load here: neither tool
# contract models an I/O boundary condition.

# DR-0003: 16 MHz external clock, M = 16 phases per conversion at 1 MS/s.
create_clock -name clk -period 62.5000 [get_ports clk]
