#!/usr/bin/env python3
"""The committed SAR-sequencer gate-level netlists must match a fresh
`klt synthesize` run of `design/sar-logic/rtl/sar_ctrl.v` (issue #272,
DR-0023 follow-on (a)).

    python3 -m unittest discover -s sim/tests -v

This is the same "generator is the source of truth, diff a fresh run against
the committed artifact" discipline `test_sar_logic_netlist.py` already
enforces for the rung-1 ideal-XSPICE model, applied to the rung-3 gate-level
netlist `design/sar-logic/flow/synth_sar_ctrl.py` produces.

## Why this test SKIPS on the headless CI path, unlike its rung-1 sibling

Unlike `gen_sar_logic.py` (stdlib Python, no external tool), regenerating the
gate netlist needs `klt synthesize` (Yosys + bundled ABC) resolving a real
gf180mcu standard-cell liberty file -- i.e. `klt` on `$PATH` *and* an
installed PDK. `.github/workflows/ci.yml`'s own header is explicit that the
default PR path installs neither (`klt` has no PyPI release yet, same
constraint that already excludes `layout/drc/run_drc.py` and
`layout/lvs/run_lvs.py` from execution there), so this test's `setUpClass`
skips cleanly (not a failure) when either tool or the PDK is unavailable,
rather than either hanging the headless run or producing a false failure
that carries no signal about whether the netlist actually drifted.

Where it DOES run: any environment with `klt`, `yosys`, and the gf180mcu PDK
on `$PATH` / resolvable (a contributor's machine per
`docs/environment-setup.md`, or a future CI job that installs `klt` --
tracked by the same follow-on issue that owns the gate-level corner-grid
replay `design/sar-logic/rtl/README.md`'s "Verification performed" section
points at). `sim/selftest.sh`'s stage 1 (this discovery command) already runs
in both places, so no new wiring is needed once `klt` becomes CI-installable.

## Why re-running the driver script IS the check

`design/sar-logic/flow/synth_sar_ctrl.py` normally writes its netlist to the
committed path (`design/sar-logic/flow/sar_ctrl/netlist/sar_ctrl.<lib>.
synth.v`). So the anti-drift check is exactly: re-run the driver against a
fresh RTL read and diff the result against the committed file. A real drift
(RTL edited without re-running the flow) shows up as a changed file; a clean
run reproduces the committed bytes exactly, because `klt synthesize`'s
Yosys/ABC recipe and the PDK's liberty file are both pinned inputs (see the
committed records under `design/sar-logic/flow/sar_ctrl/records/` for the
exact tool/PDK versions this was last generated against).

## Isolation from the committed tree (issue #287)

This test invokes the driver with `--out-dir <tmp>` (a `tempfile.
TemporaryDirectory` outside the repo) and `--no-record`, so the fresh
synthesis run this test's own comparison depends on never writes through the
driver's real, tracked `netlist/`/`reports/` output paths -- running this
test (or `npm run check:ci`, which includes it) cannot leave the working
tree dirty, regardless of whether the comparison below passes or fails.

## Yosys-version-preamble tolerance (issue #287, AC #3, option (a))

The committed netlists embed the exact `yosys -V` string that produced them
as their first line (`/* Generated by Yosys <version> ... */`). Any
environment whose installed `yosys` differs from that exact build -- a
different point release, a different git sha, a different host toolchain --
would otherwise report spurious "drift" on that line alone, even with
byte-identical synthesized logic. This test normalizes (strips) that one
preamble line from both sides before comparing, so the comparison is
tolerant of a `yosys` version difference and still asserts the synthesized
logic itself -- the actual concern of this test -- is unchanged. A genuine
RTL/netlist drift still fails: the preamble is the only line stripped, and
it never appears anywhere the synthesized logic itself would change.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

FLOW_SCRIPT = REPO / "design" / "sar-logic" / "flow" / "synth_sar_ctrl.py"
NETLIST_DIR = REPO / "design" / "sar-logic" / "flow" / "sar_ctrl" / "netlist"
NETLISTS = {
    "mcu7t5v0": NETLIST_DIR / "sar_ctrl.mcu7t5v0.synth.v",
    "mcu9t5v0": NETLIST_DIR / "sar_ctrl.mcu9t5v0.synth.v",
}

_YOSYS_PREAMBLE_RE = re.compile(r"^/\* Generated by Yosys .*\*/\n", re.MULTILINE)


def _normalize_yosys_preamble(text: str) -> str:
    """Strip the `/* Generated by Yosys <version> ... */` preamble line --
    see this module's "Yosys-version-preamble tolerance" docstring section."""
    return _YOSYS_PREAMBLE_RE.sub("", text, count=1)


def _tool_available(name: str) -> bool:
    return shutil.which(name) is not None


class GateNetlistDriftTests(unittest.TestCase):
    """PDK/`klt`/`yosys`-dependent -- see module docstring for why this
    SKIPS (not fails) when the toolchain is unavailable."""

    @classmethod
    def setUpClass(cls):
        for tool in ("klt", "yosys"):
            if not _tool_available(tool):
                raise unittest.SkipTest(
                    f"{tool!r} not found on $PATH -- see "
                    "design/sar-logic/flow/synth_sar_ctrl.py's module docstring "
                    "and docs/environment-setup.md"
                )
        from sim.harness.pdk import PdkNotFound, find_pdk  # noqa: PLC0415

        try:
            find_pdk()
        except PdkNotFound as exc:
            raise unittest.SkipTest(str(exc)) from exc

        for lib, path in NETLISTS.items():
            if not path.is_file():
                raise AssertionError(f"committed netlist missing for {lib}: {path}")

    def test_committed_netlists_match_a_fresh_synthesis(self):
        committed = {lib: path.read_text() for lib, path in NETLISTS.items()}
        with tempfile.TemporaryDirectory(prefix="sar_ctrl_gate_netlist_drift_") as tmp:
            out_dir = Path(tmp) / "out"
            result = subprocess.run(
                [
                    sys.executable,
                    str(FLOW_SCRIPT),
                    "--no-record",
                    "--out-dir",
                    str(out_dir),
                ],
                cwd=REPO,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(
                result.returncode,
                0,
                f"synth_sar_ctrl.py exited {result.returncode}:\n"
                f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}",
            )
            for lib, path in NETLISTS.items():
                with self.subTest(library=lib):
                    fresh_path = out_dir / "netlist" / path.name
                    self.assertTrue(
                        fresh_path.is_file(),
                        f"fresh synthesis did not write {fresh_path}",
                    )
                    self.assertEqual(
                        _normalize_yosys_preamble(fresh_path.read_text()),
                        _normalize_yosys_preamble(committed[lib]),
                        f"{path} is stale relative to design/sar-logic/rtl/sar_ctrl.v -- "
                        f"run: python3 {FLOW_SCRIPT.relative_to(REPO)}",
                    )


if __name__ == "__main__":
    unittest.main()
