#!/usr/bin/env python3
"""Draw the array/routing consequence of #238's candidate acquisition-leg
T-gate width -- issue #248 (item 5 of 5 deferred by
`sim/dr0019-cu-sweep-findings.md` Sec 4).

WHAT THIS MEASURES
-------------------
`sim/dr0019-cu-sweep/gen_cu_variant.py` already answers "what does the
candidate width cost the SCHEMATIC-level dynamic rows" for four of the five
deferred quantities (`--acq-switch-scale`, applied to the `Xsi` T-gate line
`design/adc-top/gen_adc_top.py` emits at the ratified geometry). This script
is the fifth: what does the SAME candidate geometry cost the LAYOUT, i.e.
`layout/adc-top/`'s array area and routing.

It reuses `layout/adc-top/gen_adc_top.py`'s own `build()` unmodified --
confirmed by reading `layout/adc-top/lib/place.draw_devices` and
`lib/geometry.draw_mosfet` directly (not assumed) that every MOSFET is drawn
at its OWN flattened `w`/`l` (`geo.draw_mosfet(..., w=dev.w_nm, l=dev.l_nm,
...)`), not at a hardcoded pitch tuned to the ratified 10u/20u width, and
that `build()`'s only netlist-shape assertion is a device COUNT check
(`len(mos) != 296`), not a width check -- so a widened-but-not-added-or-
removed `Xsi` T-gate reaches `build()` unmodified and is drawn as a
genuinely wider gate/active island. This is therefore a full re-layout
(measured, `klt`-verified geometry), not a parametric estimate.

THE CANDIDATE NETLIST
----------------------
Same technique `gen_cu_variant.py` uses for the sim decks: locate the exact
`Xsi` line `design/adc-top/adc_top.spice` (GENERATED by
`design/adc-top/gen_adc_top.py`, confirmed by that file's own header) emits
for the CDAC cell's fourth (input/acquisition) leg, assert it appears
exactly once, and substitute ONLY that line's `wn`/`wp` --
`ACQ_LEG_LINE`/`ACQ_LEG_CANDIDATE` below, at the literal 2.068x widened
values #211/#238 name (`10u`/`20u` -> `20.68u`/`41.36u`). The release/
V_REF/GND legs (`Xsr`/`Xsh`/`Xsl`) and the top-plate `V_cm` switch
(`adc_tp_sw`, which shares the SAME `CDAC_SW_WN`/`WP` module constant in
`design/adc-top/gen_adc_top.py`, but is NOT the acquisition leg #211's
orthogonal control isolates) are left at the ratified 10u/20u -- exactly the
same isolation `gen_cu_variant.py --acq-switch-scale` performs, so this
script's candidate netlist is bit-for-bit the layout counterpart of the
netlist `sim/dr0014-sampling/records/20260825-015032-446a3c4.md` already
measured on the schematic side.

`design/adc-top/adc_top.spice` is NOT edited -- the candidate text is
written to this directory's own `adc_top.candidate.spice` (kept for
provenance, not a temp file) and `nl.parse()`d from there; only
`layout/adc-top/gen_adc_top.build()` runs against the result. The ratified
`layout/adc-top/adc_top.gds`/`area.json` this repo ships are untouched.

OUTPUTS (layout/adc-top/candidates/acq-leg-2.068x/)
-----------------------------------------------------
    adc_top.candidate.spice   the candidate design/adc-top/adc_top.spice,
                               for provenance -- diff it against the ratified
                               file to see exactly what changed (one line)
    adc_top.gds / adc_block.gds        candidate-geometry layout
    adc_top.ref.spice / adc_block.ref.spice   flat LVS reference, generated
                               from the SAME candidate netlist (so LVS
                               proves the drawn geometry matches the
                               candidate design, exactly like the ratified
                               flow's own claim)
    adc_top.lvs.json / adc_block.lvs.json     `klt lvs` request documents
    area.json                  as-drawn area tally, same schema as
                               `layout/adc-top/area.json`

Not written by this script, but committed alongside it as evidence (see
`records/`): `adc_top.spice`/`adc_block.spice` (`klt extract`'s output,
exactly like the ratified `layout/adc-top/adc_top.spice`/`adc_block.spice`
are that same tool's output, not a design netlist copy) and
`reports/*.drc.json` / `*.extract.json` / `*.lvs.json` (the raw `klt`
output the record's Results table summarizes).

Verification (run by hand, not by this script -- it only draws):

    klt drc layout/adc-top/candidates/acq-leg-2.068x/adc_top.gds \\
        --deck gf180mcu --format json
    klt drc layout/adc-top/candidates/acq-leg-2.068x/adc_block.gds \\
        --deck gf180mcu --format json
    klt extract layout/adc-top/candidates/acq-leg-2.068x/adc_top.gds \\
        --deck gf180mcu -o layout/adc-top/candidates/acq-leg-2.068x/adc_top.spice \\
        --format json
    klt lvs layout/adc-top/candidates/acq-leg-2.068x/adc_top.lvs.json --format json
    (and the same extract/lvs pair for adc_block)

Usage::

    KP="$(dirname "$(readlink -f "$(command -v klt)")")/python"
    "$KP" layout/adc-top/candidates/gen_acq_leg_candidate.py

Stdlib + `klayout.db`, exactly like `layout/adc-top/gen_adc_top.py` itself
(run it with the same interpreter `klt` uses).
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ADC_TOP_DIR = os.path.dirname(HERE)  # layout/adc-top

#: The fourth-leg (`Xsi`) T-gate line, exactly as `design/adc-top/
#: gen_adc_top.py` emits it at the ratified geometry (line 120 of the
#: checked-in `design/adc-top/adc_top.spice`) -- the SAME anchor
#: `sim/dr0019-cu-sweep/gen_cu_variant.py`'s `ACQ_LEG_LINE` uses, so this
#: script's candidate netlist isolates the identical device that record's
#: schematic-side evidence does.
ACQ_LEG_LINE = "Xsi vin  bp gn_in  gp_in  vdd adc_tgate wn=10u wp=20u"
#: #211/#238's literal candidate widths: 2.068x the ratified 10u/20u.
ACQ_LEG_CANDIDATE = "Xsi vin  bp gn_in  gp_in  vdd adc_tgate wn=20.68u wp=41.36u"


def _load_layout_generator():
    """Import `layout/adc-top/gen_adc_top.py` by path (its directory name,
    `adc-top`, is not a legal package identifier)."""
    sys.path.insert(0, ADC_TOP_DIR)
    path = os.path.join(ADC_TOP_DIR, "gen_adc_top.py")
    spec = importlib.util.spec_from_file_location("gen_adc_top_acq_leg", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def candidate_netlist_text(nl) -> tuple[str, str]:
    """The ratified `design/adc-top/adc_top.spice` text with ONLY the
    `Xsi` fourth-leg line widened. Returns `(text, source_path)`."""
    design = nl.design_dir(ADC_TOP_DIR)
    source_path = os.path.join(design, "adc-top", "adc_top.spice")
    with open(source_path, encoding="utf-8") as fh:
        text = fh.read()
    hits = text.count(ACQ_LEG_LINE)
    if hits != 1:
        raise SystemExit(
            f"error: expected exactly one {ACQ_LEG_LINE!r} in {source_path}, "
            f"found {hits} -- design/adc-top/gen_adc_top.py's cell emission "
            "has changed and this substitution is no longer anchored"
        )
    return text.replace(ACQ_LEG_LINE, ACQ_LEG_CANDIDATE), source_path


def main() -> int:
    g = _load_layout_generator()
    nl = g.nl
    geo = g.geo

    outdir = os.path.join(HERE, "acq-leg-2.068x")
    os.makedirs(outdir, exist_ok=True)
    text, source_path = candidate_netlist_text(nl)
    candidate_path = os.path.join(outdir, "adc_top.candidate.spice")
    with open(candidate_path, "w", encoding="utf-8") as fh:
        fh.write(
            "* GENERATED by layout/adc-top/candidates/gen_acq_leg_candidate.py\n"
            f"* from {os.path.relpath(source_path, ADC_TOP_DIR)} with ONLY the\n"
            "* Xsi (fourth-leg / acquisition) T-gate widened 2.068x (10u/20u ->\n"
            "* 20.68u/41.36u), per issue #248 -- do not edit; not the ratified\n"
            "* design/adc-top/adc_top.spice, which this file does not replace.\n"
            "*\n" + text
        )

    subckts = nl.parse(candidate_path)
    g.block_subckt(subckts)
    comparator_subckts = nl.parse(
        os.path.join(nl.design_dir(ADC_TOP_DIR), "comparator", "comparator.spice")
    )

    tally_info = None
    for key, cell_name, cmp_subckts in (
        ("adc_top", g.CELL_NAME, None),
        ("adc_block", g.BLOCK_CELL_NAME, comparator_subckts),
    ):
        layout, info = g.build(subckts, cmp_subckts, cell_name=cell_name)
        assert layout.dbu == geo.DBU_UM, f"dbu drifted to {layout.dbu}"
        layout.write(os.path.join(outdir, f"{key}.gds"), geo.save_options())
        g.write_reference(os.path.join(outdir, f"{key}.ref.spice"), info, cell_name, key)
        g.write_request(os.path.join(outdir, f"{key}.lvs.json"), cell_name, key)
        box = layout.cell(cell_name).bbox()
        print(
            f"wrote {key}.gds  transistors={info['transistor_count']}  "
            f"caps={info['cap_count']}  "
            f"{box.width() * geo.DBU_UM:.1f} x {box.height() * geo.DBU_UM:.1f} um "
            f"= {geo.area_um2(box) / 1e6:.5f} mm^2"
        )
        tally_info = info

    census: dict[str, int] = {}
    for group in tally_info["assignment"].values():
        census[group] = census.get(group, 0) + 1
    tally = {
        "_comment": [
            "As-drawn area tally for the candidate geometry #238 item 5 / issue",
            "#248 measures: the ratified design/adc-top/adc_top.spice with ONLY",
            "the CDAC cell's fourth (input/acquisition) Xsi T-gate widened 2.068x",
            "(10u/20u -> 20.68u/41.36u), release/V_REF/GND legs and the top-plate",
            "V_cm switch left at the ratified 10u/20u. Written by",
            "layout/adc-top/candidates/gen_acq_leg_candidate.py. Same schema as",
            "layout/adc-top/area.json (the ratified geometry's own tally) so the",
            "two are directly comparable field-for-field.",
            "",
            "NOT a replacement for layout/adc-top/area.json -- this is a",
            "candidate-geometry measurement, not the ratified block's own record.",
        ],
        "areas_um2": tally_info["areas"],
        "dimensions_um": tally_info["dimensions_um"],
        "transistor_count": tally_info["transistor_count"],
        "unit_cap_device_count": tally_info["cap_count"],
        "unit_cap_positions_per_side": g.ARRAY_COLS * g.ARRAY_ROWS,
        "unit_cap_census_per_side": census,
    }
    with open(os.path.join(outdir, "area.json"), "w", encoding="utf-8") as fh:
        json.dump(tally, fh, indent=2, sort_keys=True)
        fh.write("\n")
    print(f"  unit-cap census per side: {census}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
