#!/usr/bin/env python3
"""Enforce the "results are append-only evidence" rule (CLAUDE.md,
sim/README.md "Append-only rule") mechanically.

Diffs HEAD against its merge base with the base branch and fails when any
file under a directory named `records/` -- anywhere in the tree (sim/*/records,
signoff/records, layout/*/records, layout/adc-top/*/records,
design/*/.../records, ...) -- is modified, renamed, deleted or type-changed.
Added files pass. Directories are discovered by name rather than listed, so a
new `records/` directory is covered automatically. `signoff/evidence` is NOT
guarded: it is regenerated by `signoff/run_signoff.py --regen`, not append-only.

A correction goes in as a NEW record that cites the old one via `Supersedes:`.

Escape hatch (default: none). A deliberate, reviewed exception is a line in
`sim/tools/append_only_allowlist.txt`:

    <repo-relative path>  # <justification, mandatory>

The allowlist is a committed file, so the exemption is visible in the same PR
diff a reviewer is already reading. An entry with no justification is an error.
Renames are matched on either the old or the new path.

Base selection: `--base REF`, else `origin/$GITHUB_BASE_REF` (set on pull
requests), else `origin/main`, else `main`. Needs the base ref to be fetched
(ci.yml checks out with fetch-depth: 0).

Stdlib-only, no PDK / ngspice / klt, so it belongs on the headless CI path.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ALLOWLIST_REL = "sim/tools/append_only_allowlist.txt"
GUARDED_DIR_NAME = "records"


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(f"error: git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout


def _ref_exists(repo: Path, ref: str) -> bool:
    proc = subprocess.run(
        ["git", "-C", str(repo), "rev-parse", "--verify", "--quiet", ref + "^{commit}"],
        capture_output=True, text=True, check=False,
    )
    return proc.returncode == 0


def default_base(repo: Path) -> str:
    candidates = []
    if os.environ.get("GITHUB_BASE_REF"):
        candidates.append(f"origin/{os.environ['GITHUB_BASE_REF']}")
    candidates += ["origin/main", "main"]
    for ref in candidates:
        if _ref_exists(repo, ref):
            return ref
    raise SystemExit(
        "error: no base ref found (tried " + ", ".join(candidates) + "); "
        "pass --base REF, and make sure history is fetched (fetch-depth: 0)"
    )


def is_record_path(path: str) -> bool:
    """True if any directory component of `path` is named `records`."""
    return GUARDED_DIR_NAME in path.split("/")[:-1]


def load_allowlist(text: str) -> set[str]:
    allowed: set[str] = set()
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        path, sep, why = line.partition("#")
        if not sep or not why.strip():
            raise SystemExit(
                f"error: {ALLOWLIST_REL}:{lineno}: entry needs a "
                "'# justification'"
            )
        allowed.add(path.strip())
    return allowed


def find_violations(repo: Path, base: str, allowlist: set[str]) -> list[str]:
    """Return one message per non-append change to a guarded record."""
    out = _git(repo, "diff", "--name-status", "-M", "-z", f"{base}...HEAD")
    fields = out.split("\0")
    violations: list[str] = []
    i = 0
    while i < len(fields) and fields[i]:
        status = fields[i]
        kind = status[0]
        if kind in "RC":
            paths = [fields[i + 1], fields[i + 2]]
            i += 3
        else:
            paths = [fields[i + 1]]
            i += 2
        if kind in "AC":  # added (or copied-to): append, allowed
            continue
        if not any(is_record_path(p) for p in paths):
            continue
        if any(p in allowlist for p in paths):
            continue
        label = {"M": "modified", "D": "deleted", "R": "renamed", "T": "type-changed"}.get(kind, kind)
        violations.append(f"{label}: {' -> '.join(paths)}")
    return violations


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--base", help="base ref to diff against (merge-base is used)")
    ap.add_argument("--repo", type=Path, default=REPO_ROOT, help=argparse.SUPPRESS)
    args = ap.parse_args(argv)

    repo = args.repo
    base = args.base or default_base(repo)
    allow_file = repo / ALLOWLIST_REL
    allowlist = load_allowlist(allow_file.read_text(encoding="utf-8")) if allow_file.exists() else set()

    violations = find_violations(repo, base, allowlist)
    if violations:
        print(f"FAIL: records are append-only; {len(violations)} change(s) vs {base}:")
        for v in violations:
            print(f"  {v}")
        print(
            "Add a new record that cites the old one via 'Supersedes:' instead "
            f"(sim/README.md 'Append-only rule'). A reviewed exception goes in {ALLOWLIST_REL}."
        )
        return 1
    print(f"ok: no record under a '{GUARDED_DIR_NAME}/' directory was modified, renamed or deleted vs {base}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
