#!/usr/bin/env python3
"""Generate the synchronous SAR control-logic netlists (issue #11).

Single source of truth for three committed artifacts:

  design/sar-logic/sar_ctrl.spice                              the subckt library
  sim/sar-logic-functional/testbench/tb_sar_logic_functional.spice
  sim/sar-logic-timing/testbench/tb_sar_logic_timing.spice

The corner runner consumes *self-contained* netlist fragments -- `.include` is
rejected by `sim/harness/testbench.py` on purpose, so a testbench cannot pull
the DUT in by reference and must carry it inline. Hand-maintaining three copies
of a 9-slice, 108-control decode is exactly how a testbench silently drifts
from the design it claims to verify, so the copies are generated instead and
`sim/tests/test_sar_logic_netlist.py` fails CI if a committed file stops
matching this generator.

Usage:
    python3 design/sar-logic/gen_sar_logic.py            # write the files
    python3 design/sar-logic/gen_sar_logic.py --check    # exit 1 if stale
    python3 design/sar-logic/gen_sar_logic.py --stdout library

Architecture implemented here is fixed by ratified decision records; this file
implements them, it does not choose them:

  DR-0003  external clock, M = 16  -> 16 phases per conversion
  DR-0005  10-bit parallel output register in scope, SPI deferred
  DR-0006  MCS / Vcm switching, top-plate sampling, free MSB, 9 switched
           weights (256..1) per side, mode-dependent side switching
  DR-0008  synchronous SAR logic (this issue)
  DR-0009  no redundancy / plain binary weighting (this issue)
  DR-0010  fidelity ladder; this netlist is rung 1 (ideal XSPICE digital)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Trial i (i = 1..9) engages the weight-w cell, w = 2**(9-i): 256..1.
WEIGHTS = [2 ** (9 - i) for i in range(1, 10)]
SIDES = ("p", "n")

# Bit-cycle phase map, M = 16 (DR-0003 / README Latency row:
# 4 sample + 10 bit trials + 2 reset/output).
PH_SAMPLE = (0, 1, 2, 3)
PH_TRIAL0 = 4  # free-MSB trial: comparator decides sign of the sampled residue
PH_LAST_TRIAL = 13
PH_LOAD = 14  # output register loads here (visible from ph15)
PH_DRDY = 15

# ---------------------------------------------------------------------------
# gate-level timing of the rung-1 model
#
# These are *ideal* placeholders, not gf180mcu numbers. The measured
# gf180mcu_fd_sc_mcu7t5v0 clk->Q + logic-path delay over the full PVT grid is
# a separate evidence record (sim/sar-logic-cell-delay/); DR-0010 states which
# rung owns which claim. Values here are chosen small against the 62.5 ns bit
# cycle so the rung-1 model tests *sequencing*, not timing.
# ---------------------------------------------------------------------------
T_CLK_Q = "0.5n"
T_GATE = "0.2n"


def _ports_ctrl_digital() -> list[str]:
    """Digital port list of `sar_ctrl` (event nodes)."""
    ports = ["clk", "start", "mode", "cmp", "samp", "drdy"]
    ports += [f"b{b}" for b in range(9, -1, -1)]
    for s in SIDES:
        for w in WEIGHTS:
            ports += [f"rel_{w}{s}", f"hi_{w}{s}", f"lo_{w}{s}"]
    return ports


def _ports_ctrl_analog() -> list[str]:
    """Analog port list of `sar_ctrl_a`.

    Switch-driver names follow design/cdac/cdac_array.sch exactly: in
    `sel_hi_n_256p` the *first* p/n is the transistor polarity of the T-gate
    leg (n = NMOS gate, active high; p = PMOS gate, active low) and the
    *trailing* p/n is the CDAC side. DR-0006's Consequences require `rel` to be
    driven per weight and per side; the schematic draws `rel_n`/`rel_p` as one
    shared pair as a two-cell drawing economy, and says #11 owns the real
    decode -- which is what the per-weight/per-side names below are.

    Only the NMOS-gate (active-high) half of each T-gate leg leaves the
    controller: 54 nets, not 108. The complementary PMOS gate is generated by
    `sar_tgate_drv` local to the CDAC cell it drives. Routing both polarities
    from the controller would double the control-bus width across the array
    floorplan (#16) to save one inverter per leg, and a long complementary
    pair also has to be skew-matched, which a local inverter does not.
    """
    ports = ["clk", "start", "mode", "cmp", "samp", "drdy"]
    ports += [f"c{b}" for b in range(9, -1, -1)]
    for s in SIDES:
        for w in WEIGHTS:
            ports += [
                f"rel_n_{w}{s}",
                f"sel_hi_n_{w}{s}",
                f"sel_lo_n_{w}{s}",
            ]
    return ports


def _wrap(prefix: str, items: list[str], width: int = 74) -> list[str]:
    """Emit `prefix` + items as continuation-wrapped netlist lines."""
    lines: list[str] = []
    cur = prefix
    for item in items:
        if len(cur) + 1 + len(item) > width and cur.strip() not in ("+", ""):
            lines.append(cur)
            cur = "+"
        cur += " " + item
    lines.append(cur)
    return lines


def library() -> str:
    """The reusable subckt library: `design/sar-logic/sar_ctrl.spice`."""
    L: list[str] = []
    a = L.append

    a("* ------------------------------------------------------------------")
    a("* sar_ctrl.spice -- synchronous SAR control logic, rung-1 abstraction")
    a("*")
    a("* GENERATED by design/sar-logic/gen_sar_logic.py -- do not edit.")
    a("*")
    a("* Ideal XSPICE event-driven digital primitives (digital.cm: d_dff,")
    a("* d_and, d_or, d_inverter) plus adc_bridge/dac_bridge at the analog")
    a("* boundary. This is rung 1 of the fidelity ladder in DR-0010: it fixes")
    a("* the SEQUENCING and the SWITCH DECODE, and deliberately says nothing")
    a("* about gf180mcu gate delay (rung 3 / sim/sar-logic-cell-delay/ owns")
    a("* that).")
    a("*")
    a("* Conversion, M = 16 clocks (DR-0003):")
    a("*   ph0..ph3   sample   (samp asserted; every bottom plate at Vcm)")
    a("*   ph4        trial 1  free MSB -- no array switching at all, the")
    a("*                       comparator decides the sign of the sampled")
    a("*                       residue (DR-0006 top-plate sampling)")
    a("*   ph5..ph13  trials 2..10, weights 256,128,...,1 engaged in turn")
    a("*   ph14       output register loads the 10 decisions")
    a("*   ph15       drdy asserted; array released back to Vcm")
    a("*")
    a("* Switch decode per weight w and side s, from the slice's own engage")
    a("* flag `eng` and direction bit `dir` (= the decision of the PREVIOUS")
    a("* trial, which is also that trial's output bit):")
    a("*   rel = !eng                     bottom plate parked at Vcm")
    a("*   p-side:  hi = eng & !dir       -> V_REF      lo = eng & dir  -> GND")
    a("*   n-side:  hi = eng &  dir       -> V_REF      lo = eng & !dir -> GND")
    a("*   n-side is additionally gated by `mode` (1 = differential): in")
    a("*   single-ended mode every n-side cell stays released to Vcm for the")
    a("*   whole conversion, per DR-0006 -- driving it too would double every")
    a("*   step and cost a bit of resolution.")
    a("*")
    a("* Sign convention: cmp = 1 when top_p > top_n. dir = 1 therefore means")
    a("* 'residue positive, subtract this weight', i.e. p-side down / n-side")
    a("* up, which is the `p-side lo` / `n-side hi` decode above.")
    a("* ------------------------------------------------------------------")
    a("")
    a("* --- ideal digital primitives -------------------------------------")
    a(f".model sarl_dff d_dff(clk_delay={T_CLK_Q} set_delay={T_CLK_Q}")
    a(f"+ reset_delay={T_CLK_Q} ic=0 rise_delay={T_CLK_Q} fall_delay={T_CLK_Q})")
    a(f".model sarl_dff1 d_dff(clk_delay={T_CLK_Q} set_delay={T_CLK_Q}")
    a(f"+ reset_delay={T_CLK_Q} ic=1 rise_delay={T_CLK_Q} fall_delay={T_CLK_Q})")
    a(f".model sarl_and d_and(rise_delay={T_GATE} fall_delay={T_GATE} input_load=0)")
    a(f".model sarl_or d_or(rise_delay={T_GATE} fall_delay={T_GATE} input_load=0)")
    a(f".model sarl_inv d_inverter(rise_delay={T_GATE} fall_delay={T_GATE}")
    a("+ input_load=0)")
    a("")
    a("* --- enabled bit register -----------------------------------------")
    a("* Captures `d` on the clock edge that ENDS the phase in which `en` is")
    a("* asserted, and holds otherwise. Written as an explicit D-mux rather")
    a("* than a gated clock: gating the clock with a phase signal that itself")
    a("* changes one gate delay after the clock edge creates a spurious")
    a("* rising edge on the gated clock, which is a real bug in a real")
    a("* implementation, not just in this model.")
    a(".subckt sar_bitreg clk d en q qb")
    a("a_inv en enb sarl_inv")
    a("a_sel [en d] dsel sarl_and")
    a("a_hold [enb q] dhold sarl_and")
    a("a_mux [dsel dhold] dnext sarl_or")
    a("a_ff dnext clk NULL NULL q qb sarl_dff")
    a(".ends sar_bitreg")
    a("")
    a("* --- one bit slice: engage flag + direction bit + switch decode -----")
    a("* `arm`     one-hot phase pulse of the trial BEFORE this slice's own")
    a("*           trial: the slice engages on the edge entering its trial,")
    a("*           and the direction bit captures the decision made during")
    a("*           `arm` (which is also this bit position's output bit).")
    a("* `endconv` forces the engage flag low on the edge leaving the last")
    a("*           trial, releasing the whole array back to Vcm for the next")
    a("*           sample phase.")
    a(".subckt sar_slice clk cmp mode arm endconv dir dirb")
    a("+ rel_p hi_p lo_p rel_n hi_n lo_n")
    a("a_set [arm eng] eng_set sarl_or")
    a("a_ninv endconv nend sarl_inv")
    a("a_keep [eng_set nend] eng_d sarl_and")
    a("a_ff eng_d clk NULL NULL eng engb sarl_dff")
    a("xdir clk cmp arm dir dirb sar_bitreg")
    a("* p side: always driven")
    a("a_relp eng rel_p sarl_inv")
    a("a_hip [eng dirb] hi_p sarl_and")
    a("a_lop [eng dir] lo_p sarl_and")
    a("* n side: driven only in differential mode (DR-0006)")
    a("a_engn [eng mode] engn sarl_and")
    a("a_reln engn rel_n sarl_inv")
    a("a_hin [engn dir] hi_n sarl_and")
    a("a_lon [engn dirb] lo_n sarl_and")
    a(".ends sar_slice")
    a("")
    a("* --- 16-phase one-hot sequencer ------------------------------------")
    a("* A one-hot ring, seeded by ph15's ic=1 so the very first clock edge")
    a("* enters ph0 (sample) with exactly one token in the ring. `start`")
    a("* forces a synchronous restart: it sets stage 0 and clears every other")
    a("* stage on the same edge, so an asserted `start` cannot inject a")
    a("* SECOND token alongside the circulating one.")
    a(".subckt sar_seq clk start " + " ".join(f"ph{k}" for k in range(16)))
    a("a_nstart start nstart sarl_inv")
    a("a_d0 [ph15 start] d0 sarl_or")
    a("a_ff0 d0 clk NULL NULL ph0 ph0b sarl_dff")
    for k in range(1, 16):
        model = "sarl_dff1" if k == 15 else "sarl_dff"
        a(f"a_d{k} [ph{k - 1} nstart] d{k} sarl_and")
        a(f"a_ff{k} d{k} clk NULL NULL ph{k} ph{k}b {model}")
    a(".ends sar_seq")
    a("")
    a("* --- digital top ----------------------------------------------------")
    L += _wrap(".subckt sar_ctrl", _ports_ctrl_digital())
    a("xseq clk start " + " ".join(f"ph{k}" for k in range(16)) + " sar_seq")
    a("a_samp [" + " ".join(f"ph{k}" for k in PH_SAMPLE) + "] samp sarl_or")
    a(f"a_drdy ph{PH_DRDY} drdy_n sarl_inv")
    a("a_drdy2 drdy_n drdy sarl_inv")
    for i, w in enumerate(WEIGHTS, start=1):
        arm = PH_TRIAL0 + i - 1  # ph4..ph12
        bit = 10 - i  # b9..b1
        a(
            f"xs{w} clk cmp mode ph{arm} ph{PH_LAST_TRIAL} q{bit} q{bit}b "
            f"rel_{w}p hi_{w}p lo_{w}p rel_{w}n hi_{w}n lo_{w}n sar_slice"
        )
    a(f"xb0 clk cmp ph{PH_LAST_TRIAL} q0 q0b sar_bitreg")
    a("* 10-bit parallel output register (DR-0005: in scope, SPI deferred)")
    for b in range(9, -1, -1):
        a(f"xo{b} clk q{b} ph{PH_LOAD} b{b} b{b}b sar_bitreg")
    a(".ends sar_ctrl")
    a("")
    a("* --- analog-boundary wrapper ----------------------------------------")
    a("* Presents the controller at the analog boundary with the port names")
    a("* design/cdac/cdac_array.sch uses, so the two connect directly. Only")
    a("* the NMOS-gate (active-high) half of each T-gate leg is routed out of")
    a("* the controller; `sar_tgate_drv` below makes the PMOS gate locally at")
    a("* the cell. Bridges are VECTOR instances on purpose: 54 scalar")
    a("* dac_bridges would put 54 separate sources in the analog matrix.")
    L += _wrap(".subckt sar_ctrl_a", _ports_ctrl_analog())
    a("a_in [clk start mode cmp] [dclk dstart dmode dcmp] sarl_adc")
    dports = ["dclk", "dstart", "dmode", "dcmp", "dsamp", "ddrdy"]
    dports += [f"db{b}" for b in range(9, -1, -1)]
    for s in SIDES:
        for w in WEIGHTS:
            dports += [f"drel_{w}{s}", f"dhi_{w}{s}", f"dlo_{w}{s}"]
    L += _wrap("xctrl", dports + ["sar_ctrl"])
    outn = ["dsamp", "ddrdy"] + [f"db{b}" for b in range(9, -1, -1)]
    anaout = ["samp", "drdy"] + [f"c{b}" for b in range(9, -1, -1)]
    L += _wrap("a_dout [" + " ".join(outn) + "]", ["[" + " ".join(anaout) + "]"])
    L[-1] += " sarl_dac"
    g_nodes, g_ports = [], []
    for s in SIDES:
        for w in WEIGHTS:
            for f, port in (("rel", "rel"), ("hi", "sel_hi"), ("lo", "sel_lo")):
                g_nodes.append(f"d{f}_{w}{s}")
                g_ports.append(f"{port}_n_{w}{s}")
    L += _wrap("a_gn [" + " ".join(g_nodes) + "]", ["[" + " ".join(g_ports) + "]"])
    L[-1] += " sarl_dac"
    a(".ends sar_ctrl_a")
    a("")
    a("* --- local T-gate driver -------------------------------------------")
    a("* One per T-gate leg, placed with the CDAC cell (#15/#16), not with")
    a("* the controller: `gn` is the controller's active-high control and")
    a("* `gp` the complementary PMOS gate. Modelled as an ideal inverter at")
    a("* rung 1; at rung 3 it is one standard-cell inverter.")
    a(".subckt sar_tgate_drv gn gp")
    a("a_adc gn dgn sarl_adc")
    a("a_inv dgn dgp sarl_inv")
    a("a_dac dgp gp sarl_dac")
    a(".ends sar_tgate_drv")
    a("")
    a("* Bridge models. Thresholds and rails track the PVT point's supply, so")
    a("* the supply axis of the corner grid actually moves something in this")
    a("* otherwise PVT-invariant model.")
    a(".model sarl_adc adc_bridge(in_low={vdd_val*0.4} in_high={vdd_val*0.6})")
    a(".model sarl_dac dac_bridge(out_low=0 out_high={vdd_val}")
    a("+ out_undef={vdd_val/2} t_rise=0.3n t_fall=0.3n)")
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------------------
# testbench harnesses
# ---------------------------------------------------------------------------

CLK_PERIOD_NS = 62.5  # M = 16 at 1 MS/s (DR-0003)
CONV_NS = 16 * CLK_PERIOD_NS  # 1 us


def _loop(tag: str, mode_expr: str, cmp_delay: str | None = None) -> list[str]:
    """One closed SAR loop: controller + ideal CDAC + ideal comparator.

    The CDAC is built behaviourally FROM THE CONTROLLER'S OWN SWITCH-DRIVER
    OUTPUTS, so the loop is not a tautology: a wrong decode (wrong direction,
    wrong side in single-ended mode, a cell that never releases) moves the top
    plate wrongly and the conversion produces the wrong code.
    """
    L: list[str] = []
    a = L.append
    ports = [f"{tag}_{p}" if p not in ("clk",) else "clk" for p in _ports_ctrl_analog()]
    # mode / start / cmp are driven locally
    ports[1] = f"{tag}_start"
    ports[2] = f"{tag}_mode"
    ports[3] = f"{tag}_cmpo"
    a(f"* ---- loop {tag} ----")
    a(f"v{tag}start {tag}_start 0 dc 0")
    a(f"v{tag}mode {tag}_mode 0 dc {mode_expr}")
    L += _wrap(f"x{tag}", ports + ["sar_ctrl_a"])
    # ideal sample-and-hold on each side
    a(f"s{tag}p {tag}_vinp {tag}_shp {tag}_samp 0 sarl_sw")
    a(f"s{tag}n {tag}_vinn {tag}_shn {tag}_samp 0 sarl_sw")
    a(f"c{tag}p {tag}_shp 0 1p")
    a(f"c{tag}n {tag}_shn 0 1p")
    # A SECOND sample-and-hold pair on a deliberately late copy of `samp`,
    # used ONLY to compute the expected code. `samp` rises at the same instant
    # `drdy` falls, so an expected code derived from the DUT's own hold node
    # changes while the drdy evaluation window is still closing, and reports a
    # spurious one-LSB error every conversion. These track ~7 ns longer, which
    # holds the expected code valid across that edge. The input moves ~0.007
    # LSB in 7 ns at the ramp rate used here, i.e. 70x below the 0.5 LSB the
    # check has to resolve.
    a(f"r{tag}sd {tag}_samp {tag}_sampd 10k")
    a(f"c{tag}sd {tag}_sampd 0 1p")
    a(f"s{tag}xp {tag}_vinp {tag}_shxp {tag}_sampd 0 sarl_sw")
    a(f"s{tag}xn {tag}_vinn {tag}_shxn {tag}_sampd 0 sarl_sw")
    a(f"c{tag}xp {tag}_shxp 0 1p")
    a(f"c{tag}xn {tag}_shxn 0 1p")
    # behavioural CDAC top plates, driven by the controller's NMOS gate drives
    for s in SIDES:
        terms = []
        for w in WEIGHTS:
            terms.append(
                f"{w}*((v({tag}_rel_n_{w}{s})*vcm+v({tag}_sel_hi_n_{w}{s})*vref)"
                f"/vdd_val-vcm)"
            )
        sh = f"{tag}_shp" if s == "p" else f"{tag}_shn"
        L += _wrap(
            f"b{tag}top{s} {tag}_topi{s} 0 V = v({sh})+(1.0/512)*(",
            [" + ".join(terms) + " )"],
        )
    # first-order DAC settling: tau = 1k * 2.56p = 2.56 ns, the survey's
    # spec/prior-art-survey.md Sec 1.4 network. Real settling over PVT is
    # sim/cdac-bit-settling/'s claim, not this model's.
    a(f"r{tag}p {tag}_topip {tag}_topp 1k")
    a(f"r{tag}n {tag}_topin {tag}_topn 1k")
    a(f"c{tag}tp {tag}_topp 0 2.56p")
    a(f"c{tag}tn {tag}_topn 0 2.56p")
    # ideal comparator
    if cmp_delay is None:
        a(
            f"b{tag}cmp {tag}_cmpo 0 V = "
            f"v({tag}_topp) > v({tag}_topn) ? vdd_val : 0"
        )
    else:
        a(
            f"b{tag}cmp {tag}_cmpi 0 V = "
            f"v({tag}_topp) > v({tag}_topn) ? vdd_val : 0"
        )
        a(
            f"t{tag}d {tag}_cmpi 0 {tag}_cmpo 0 z0=50 td={cmp_delay}"
        )
        a(f"r{tag}term {tag}_cmpo 0 50")
    # decoded output code
    terms = [f"({2 ** b})*(v({tag}_c{b})>vth ? 1 : 0)" for b in range(9, -1, -1)]
    L += _wrap(f"b{tag}code {tag}_code 0 V = ", [" + ".join(terms)])
    # switch-driver one-hot invariant, normalised to the supply: on every
    # cell, on both sides, exactly one of {rel, sel_hi, sel_lo} is asserted at
    # all times. Summed as absolute deviations over all 18 cells, so a single
    # cell that ever drives two rails at once (or none) shows up here.
    terms = []
    for s in SIDES:
        for w in WEIGHTS:
            terms.append(
                f"abs(v({tag}_rel_n_{w}{s})+v({tag}_sel_hi_n_{w}{s})"
                f"+v({tag}_sel_lo_n_{w}{s})-vdd_val)"
            )
    L += _wrap(f"b{tag}conf {tag}_conf 0 V = (", [" + ".join(terms) + ")/vdd_val"])
    # n-side activity, normalised to the supply so the bound is a count of
    # engaged cells rather than a voltage: the direct, non-inferential form of
    # DR-0006's mode-dependent rule. Single-ended must leave every n-side cell
    # released to Vcm for the whole conversion (this stays 0); differential
    # must engage all nine of them (this reaches 9 by the last trial).
    terms = [
        f"v({tag}_sel_hi_n_{w}n)+v({tag}_sel_lo_n_{w}n)" for w in WEIGHTS
    ]
    L += _wrap(f"b{tag}nside {tag}_nside 0 V = (", [" + ".join(terms) + ")/vdd_val"])
    return L


def _functional_body(nconv: int) -> list[str]:
    """Exhaustive code sweep, both input modes, in one deck."""
    L: list[str] = []
    a = L.append
    t_end_ns = nconv * CONV_NS
    a("* ==================================================================")
    a("* tb_sar_logic_functional -- exhaustive functional verification of")
    a("* the synchronous SAR controller (issue #11).")
    a("*")
    a("* GENERATED by design/sar-logic/gen_sar_logic.py -- do not edit.")
    a("*")
    a("* Two independent closed loops run in the same deck: `se` in")
    a("* single-ended mode and `df` in differential mode (DR-0006's two")
    a("* input modes, which switch a DIFFERENT NUMBER OF SIDES per trial and")
    a("* therefore need separate coverage, not one run with a flag flipped).")
    a("*")
    a(f"* Each loop converts {nconv} times. The input ramps by exactly one")
    a("* LSB of its own mode per conversion, offset half an LSB so every")
    a("* sample lands mid-code, so the run exercises every one of the 1024")
    a("* output codes exactly once -- i.e. every possible bit-trial decision")
    a("* sequence, since a plain-binary SAR with no redundancy (DR-0009) has")
    a("* exactly one decision sequence per code.")
    a("*")
    a("* All 1024 conversions are checked with two scalars per mode, not")
    a("* 1024 assertions: an error signal (converted code minus the")
    a("* closed-form ideal code of the held sample) is evaluated during every")
    a("* drdy window and its MAX and MIN over the whole run are measured. A")
    a("* single wrong conversion anywhere moves one of them by >= 1 LSB.")
    a("* ==================================================================")
    a("")
    a("* V_REF is ratiometric to the supply here: the ratified spec (README")
    a("* note [c]) makes V_REF <= V_DD a hard condition, so a fixed 3.3 V")
    a("* reference is not legal at the 2.97 V corner. Taking V_REF = V_DD")
    a("* keeps the deck legal at every point of the supply axis; the code")
    a("* check is ratiometric too, so it is unaffected.")
    a(".param vref={vdd_val}")
    a(".param vcm={vdd_val/2}")
    a(".param vth={vdd_val/2}")
    a(".param lsbse={vdd_val/1024}")
    a(".param lsbdf={vdd_val/512}")
    a(".model sarl_sw sw(vt={vdd_val/2} vh=0 ron=1 roff=1e12)")
    a("")
    a(f"vclk clk 0 pulse(0 {{vdd_val}} 0 100p 100p {CLK_PERIOD_NS / 2}n"
      f" {CLK_PERIOD_NS}n)")
    a("")
    L += _loop("se", "0")
    a("* single-ended: the p side samples V_in over 0..V_REF, the n side is")
    a("* pinned at V_cm (DR-0006). Full scale = V_REF, LSB = V_REF/1024.")
    a(f"vsein se_vinp 0 pwl(0 {{lsbse/2}} {t_end_ns}n {{vref+lsbse/2}})")
    a("vsecm se_vinn 0 dc {vcm}")
    a("bseexp se_exp 0 V = "
      "min(max(floor(v(se_shxp)/lsbse),0),1023)")
    a("bseerr se_err 0 V = v(se_drdy)>vth ? v(se_code)-v(se_exp) : 0")
    a("")
    L += _loop("df", "{vdd_val}")
    a("* differential: both pins swing +-V_REF/2 about V_cm, so the")
    a("* differential input covers +-V_REF. Full scale = 2*V_REF,")
    a("* LSB = V_REF/512, mid-scale code 512 at zero differential input.")
    a(f"vdfp df_vinp 0 pwl(0 {{vcm-vref/2+lsbdf/4}} {t_end_ns}n"
      f" {{vcm+vref/2+lsbdf/4}})")
    a(f"vdfn df_vinn 0 pwl(0 {{vcm+vref/2-lsbdf/4}} {t_end_ns}n"
      f" {{vcm-vref/2-lsbdf/4}})")
    a("bdfexp df_exp 0 V = "
      "min(max(512+floor((v(df_shxp)-v(df_shxn))/lsbdf),0),1023)")
    a("bdferr df_err 0 V = v(df_drdy)>vth ? v(df_code)-v(df_exp) : 0")
    return L


def _timing_body() -> list[str]:
    """Comparator-decision-delay margin, tie handling, cadence."""
    L: list[str] = []
    a = L.append
    a("* ==================================================================")
    a("* tb_sar_logic_timing -- what the synchronous choice actually buys,")
    a("* measured rather than asserted (issue #11, DR-0008).")
    a("*")
    a("* GENERATED by design/sar-logic/gen_sar_logic.py -- do not edit.")
    a("*")
    a("* Four single-ended loops, identical except for a delay inserted")
    a("* between the comparator\'s analog decision and the controller")
    a("* sampling it. The delay stands in for everything that has to happen")
    a("* inside one 62.5 ns bit cycle before the latching edge: DAC settling,")
    a("* comparator regeneration, and logic propagation.")
    a("*   ok   0 ns    reference")
    a("*   lt  40 ns    the whole of the ~40 ns of per-cycle slack the")
    a("*                survey (Sec 4.2) claims a 62.5 ns bit cycle has,")
    a("*                spent in one place")
    a("*   xl  50 ns    80 % of the cycle consumed -- still correct")
    a("*   bad 70 ns    DELIBERATELY past the 62.5 ns cycle: the decision")
    a("*                arrives after the edge that was supposed to latch it")
    a("*")
    a("* The 50 ns point is not the survey's original guess: an earlier draft")
    a("* of this deck used 55 ns and measured a real failure (max|err| = 2")
    a("* LSB against a >= 1 LSB threshold). Bisecting against this SAME")
    a("* behavioural DAC/comparator model found the true boundary between")
    a("* 50 ns (exact) and 52 ns (max|err| = 1 LSB, already over the 0.5 LSB")
    a("* bound). 50 ns is kept as the bracket point precisely because it is")
    a("* the largest round number this model measures as exact, not because")
    a("* it was the original guess -- CLAUDE.md requires a measured number")
    a("* here, not an assumed one. DR-0010 records the gap between the")
    a("* survey's slack estimate and this measured boundary; the shortfall")
    a("* is attributed to this testbench's RC DAC-settling model (tau =")
    a("* 2.56 ns) consuming part of the delay budget the survey treated as")
    a("* separate, not to a synchronous-logic problem.")
    a("*")
    a("* `bad` is the negative control, and it is the reason the other three")
    a("* mean anything: its check asserts the conversion IS wrong. Without a")
    a("* case that must fail, an err == 0 result on the first three would not")
    a("* show that this testbench can detect a broken conversion at all.")
    a("*")
    a("* A fifth loop, `tie`, holds its input exactly on the free-MSB")
    a("* decision threshold (v_in = V_cm to the last bit) for the whole run.")
    a("* That is the near-metastable input a real comparator resolves slowly")
    a("* or wrongly. The claim under test is NOT that the code is right --")
    a("* on an exact tie either adjacent code is correct -- but that the")
    a("* conversion still COMPLETES on schedule: drdy keeps arriving exactly")
    a("* 16 clocks apart. That is the concrete form of the row")
    a("* spec/prior-art-survey.md Sec 4.3 gives synchronous logic (\'a stalled")
    a("* decision corrupts one bit\') against asynchronous (\'a stalled")
    a("* decision stalls the whole conversion; needs a timeout/watchdog\').")
    a("* ==================================================================")
    a("")
    a(".param vref={vdd_val}")
    a(".param vcm={vdd_val/2}")
    a(".param vth={vdd_val/2}")
    a(".param lsbse={vdd_val/1024}")
    a(".model sarl_sw sw(vt={vdd_val/2} vh=0 ron=1 roff=1e12)")
    a("")
    a(f"vclk clk 0 pulse(0 {{vdd_val}} 0 100p 100p {CLK_PERIOD_NS / 2}n"
      f" {CLK_PERIOD_NS}n)")
    a("")
    for tag, delay in (("ok", None), ("lt", "40n"), ("xl", "50n"),
                       ("bad", "70n")):
        L += _loop(tag, "0", cmp_delay=delay)
        a(f"* {tag}: input ramps one LSB per conversion THROUGH mid-scale")
        a("* (codes 507..515), so the run crosses the major carry where every")
        a("* bit changes at once -- the worst case for a late decision -- and")
        a("* exercises both branches of the free-MSB trial.")
        a(f"v{tag}in {tag}_vinp 0 pwl(0 {{vcm-4.75*lsbse}} 8u"
          f" {{vcm+3.25*lsbse}})")
        a(f"v{tag}cm {tag}_vinn 0 dc {{vcm}}")
        a(f"b{tag}exp {tag}_exp 0 V = "
          f"min(max(floor(v({tag}_shxp)/lsbse),0),1023)")
        a(f"b{tag}err {tag}_err 0 V = "
          f"v({tag}_drdy)>vth ? v({tag}_code)-v({tag}_exp) : 0")
        a(f"b{tag}aerr {tag}_aerr 0 V = abs(v({tag}_err))")
        a("")
    L += _loop("tie", "0")
    a("* tie: input pinned exactly on the free-MSB threshold for the whole")
    a("* run. No code check -- either adjacent code is a correct answer to")
    a("* an exact tie. The measured claim is the cadence.")
    a("vtiein tie_vinp 0 dc {vcm}")
    a("vtiecm tie_vinn 0 dc {vcm}")
    a("* Gated by drdy, like b<tag>err above: c9..c0 hold their POWER-UP")
    a("* reset value (all zero, i.e. code 0) until the first ph14 load, and")
    a("* an earlier draft of this deck measured tie_dev unconditionally --")
    a("* which made every run report a spurious code-0 deviation of 512 for")
    a("* the ~875 ns before the first conversion's drdy, independent of")
    a("* whether the design was actually correct. Gating on drdy restricts")
    a("* the measurement to windows where the register holds a completed")
    a("* conversion's result, the same fix b<tag>err already applied above.")
    a("btiedev tie_dev 0 V = v(tie_drdy)>vth ? abs(v(tie_code)-512) : 0")
    return L


def functional(nconv: int = 1024) -> str:
    return "\n".join(_functional_body(nconv) + ["", library()])


def timing() -> str:
    return "\n".join(_timing_body() + ["", library()])


TARGETS = {
    "library": ("design/sar-logic/sar_ctrl.spice", library),
    "functional": (
        "sim/sar-logic-functional/testbench/tb_sar_logic_functional.spice",
        functional,
    ),
    "timing": (
        "sim/sar-logic-timing/testbench/tb_sar_logic_timing.spice",
        timing,
    ),
}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--check", action="store_true",
                   help="exit 1 if any committed file differs from generated")
    p.add_argument("--stdout", choices=sorted(TARGETS),
                   help="print one artifact instead of writing files")
    args = p.parse_args(argv)

    if args.stdout:
        sys.stdout.write(TARGETS[args.stdout][1]())
        return 0

    stale = []
    for name, (rel, fn) in sorted(TARGETS.items()):
        path = REPO / rel
        text = fn()
        if args.check:
            if not path.is_file() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {rel}")
    if args.check:
        for rel in stale:
            print(f"STALE: {rel}", file=sys.stderr)
        if stale:
            print("run: python3 design/sar-logic/gen_sar_logic.py",
                  file=sys.stderr)
            return 1
        print("all generated netlists are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
