#!/usr/bin/env bash
# gf180-sar-adc environment bootstrap smoke test.
#
# Verifies the xschem -> ngspice -> gf180mcu PDK toolchain end to end:
#   1. Netlists design/smoke_test.sch with xschem (headless: -n -x -q).
#   2. Generates a small PDK "include shim" (sim/smoke_test/pdk_include.spice)
#      from $PDK_ROOT / $PDK -- kept OUT of the schematic itself so
#      design/smoke_test.sch has no hardcoded, machine-specific path.
#   3. Runs the resulting netlist through ngspice in batch mode.
#
# This is the *installation* check, and it deliberately pins a single
# typical corner. It is NOT the harness's corner-sensitivity proof -- that is
# `sim/selftest.sh`, which sweeps the real PVT grid and then re-runs it with
# every model section forced to typical to prove the sweep is live. Passing
# this script says the tools are installed; it says nothing about whether
# corner switching works.
#
# PDK_ROOT / PDK are honoured if already exported; otherwise the script
# resolves the PDK itself through the harness (the same resolution order the
# corner runner uses), so a clean shell needs no hand-set environment. If the
# PDK genuinely cannot be found, it fails loudly with install instructions
# rather than half-running.
#
# Usage:
#   sim/smoke_test/run_smoke_test.sh              record the run as evidence
#   sim/smoke_test/run_smoke_test.sh --no-write   run it, record nothing
#
# Output (both appended to sim/smoke_test/smoke_test.log, append-only
# evidence per CLAUDE.md -- re-running this script adds a new dated section
# rather than overwriting prior runs):
#   - the xschem netlist run
#   - the ngspice batch run (operating-point voltages)
#
# --no-write sends that output to stdout only, leaving smoke_test.log
# untouched. It exists because an automated runner must never append to the
# evidence log: it would either commit machine-generated sections nobody
# reviewed, or (worse) produce sections that are silently discarded, so the
# tracked log stops being the record of every run. Same reason the corner
# runner has --no-write. The derived artifacts under sim/smoke_test/
# (pdk_include.spice, smoke_test.spice) are still regenerated either way --
# they are git-ignored build products, not evidence.

set -euo pipefail

NO_WRITE=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-write) NO_WRITE=1 ;;
    -h|--help) sed -n '2,41p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCH="$REPO_ROOT/design/smoke_test.sch"
RCFILE="$REPO_ROOT/design/xschemrc"
OUT_DIR="$REPO_ROOT/sim/smoke_test"
LOG="$OUT_DIR/smoke_test.log"
NETLIST="$OUT_DIR/smoke_test.spice"

# Every `tee -a "$LOG"` below becomes a plain stdout copy under --no-write.
# Redirecting the sink, rather than branching at each call site, keeps the two
# modes from drifting apart: there is exactly one code path.
if [ "$NO_WRITE" -eq 1 ]; then
  LOG=/dev/null
fi

# Self-bootstrap: an unset PDK_ROOT/PDK is not an error, it just means nothing
# has been sourced yet. Ask the harness where the PDK is -- one resolver for
# the whole repo, so the smoke test and the corner runner can never disagree
# about which PDK is under test. An explicit PDK_ROOT/PDK in the environment
# still wins, which is what makes `--print-env` and a manual export equivalent.
if [[ -z "${PDK_ROOT:-}" || -z "${PDK:-}" ]]; then
  if ! _exports="$(python3 "$REPO_ROOT/sim/run_corners.py" --print-env 2>&1)"; then
    echo "ERROR: PDK_ROOT/PDK are unset and the gf180mcu PDK could not be located." >&2
    echo "$_exports" | sed 's/^/       /' >&2
    echo "       See docs/environment-setup.md, or run:" >&2
    echo "         python3 sim/run_corners.py --check-env" >&2
    exit 1
  fi
  eval "$_exports"
  echo "resolved PDK via sim/run_corners.py --print-env: PDK_ROOT=$PDK_ROOT PDK=$PDK"
fi

for tool in xschem ngspice; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: $tool not found on PATH. See docs/environment-setup.md." >&2
    exit 1
  fi
done

MODEL_DIR="$PDK_ROOT/$PDK/libs.tech/ngspice"
if [[ ! -f "$MODEL_DIR/design.ngspice" || ! -f "$MODEL_DIR/sm141064.ngspice" ]]; then
  echo "ERROR: gf180mcu ngspice models not found under $MODEL_DIR" >&2
  echo "       Did you run 'volare fetch --pdk gf180mcu <hash>' and" >&2
  echo "       'volare enable --pdk gf180mcu <hash>'? See docs/environment-setup.md." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Generated artifact -- not the netlist itself, just the PDK path shim.
# Overwritten each run by design (it is derived, not evidence).
cat > "$OUT_DIR/pdk_include.spice" <<EOF
* Generated by run_smoke_test.sh from \$PDK_ROOT/\$PDK -- do not edit by hand.
.include $MODEL_DIR/design.ngspice
.lib $MODEL_DIR/sm141064.ngspice typical
EOF

{
  echo "===================================================================="
  echo "gf180-sar-adc smoke test run: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "PDK_ROOT=$PDK_ROOT"
  echo "PDK=$PDK"
  echo "xschem: $(xschem --version 2>&1 | head -1)"
  echo "ngspice: $(ngspice -v 2>&1 | sed -n '2p')"
  echo "===================================================================="
  if [ "$NO_WRITE" -eq 1 ]; then
    echo "--no-write: this run is NOT appended to sim/smoke_test/smoke_test.log"
  fi
} | tee -a "$LOG"

echo "-- xschem netlist --" | tee -a "$LOG"
xschem -n -x -q -r --rcfile "$RCFILE" -o "$OUT_DIR" "$SCH" 2>&1 | tee -a "$LOG"

if [[ ! -f "$NETLIST" ]]; then
  echo "ERROR: netlist not produced at $NETLIST" >&2
  exit 1
fi

echo "-- ngspice run --" | tee -a "$LOG"
(cd "$OUT_DIR" && ngspice -b "$(basename "$NETLIST")") 2>&1 | tee -a "$LOG"

echo "-- smoke test complete --" | tee -a "$LOG"
