#!/usr/bin/env bash
# gf180-sar-adc environment bootstrap smoke test.
#
# Verifies the xschem -> ngspice -> gf180mcu PDK toolchain end to end:
#   1. Netlists design/smoke_test.sch with xschem (headless: -n -x -q).
#   2. Generates a small PDK "include shim" (sim/smoke_test/pdk_include.spice)
#      from $PDK_ROOT / $PDK -- kept OUT of the schematic itself so
#      design/smoke_test.sch has no hardcoded, machine-specific path.
#   3. Runs the resulting netlist through ngspice in batch mode.
#
# This is the *installation* check, and it deliberately pins a single
# typical corner. It is NOT the harness's corner-sensitivity proof -- that is
# `sim/selftest.sh`, which sweeps the real PVT grid and then re-runs it with
# every model section forced to typical to prove the sweep is live. Passing
# this script says the tools are installed; it says nothing about whether
# corner switching works.
#
# Requires PDK_ROOT and PDK to already be set in the environment -- see
# docs/environment-setup.md, or run `source sim/env.sh`.
#
# Usage: sim/smoke_test/run_smoke_test.sh
#
# Output (both appended to sim/smoke_test/smoke_test.log, append-only
# evidence per CLAUDE.md -- re-running this script adds a new dated section
# rather than overwriting prior runs):
#   - the xschem netlist run
#   - the ngspice batch run (operating-point voltages)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCH="$REPO_ROOT/design/smoke_test.sch"
RCFILE="$REPO_ROOT/design/xschemrc"
OUT_DIR="$REPO_ROOT/sim/smoke_test"
LOG="$OUT_DIR/smoke_test.log"
NETLIST="$OUT_DIR/smoke_test.spice"

if [[ -z "${PDK_ROOT:-}" || -z "${PDK:-}" ]]; then
  echo "ERROR: PDK_ROOT and PDK must be set in the environment." >&2
  echo "       Run 'source sim/env.sh', or see docs/environment-setup.md." >&2
  exit 1
fi

for tool in xschem ngspice; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: $tool not found on PATH. See docs/environment-setup.md." >&2
    exit 1
  fi
done

MODEL_DIR="$PDK_ROOT/$PDK/libs.tech/ngspice"
if [[ ! -f "$MODEL_DIR/design.ngspice" || ! -f "$MODEL_DIR/sm141064.ngspice" ]]; then
  echo "ERROR: gf180mcu ngspice models not found under $MODEL_DIR" >&2
  echo "       Did you run 'volare fetch --pdk gf180mcu <hash>' and" >&2
  echo "       'volare enable --pdk gf180mcu <hash>'? See docs/environment-setup.md." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# Generated artifact -- not the netlist itself, just the PDK path shim.
# Overwritten each run by design (it is derived, not evidence).
cat > "$OUT_DIR/pdk_include.spice" <<EOF
* Generated by run_smoke_test.sh from \$PDK_ROOT/\$PDK -- do not edit by hand.
.include $MODEL_DIR/design.ngspice
.lib $MODEL_DIR/sm141064.ngspice typical
EOF

{
  echo "===================================================================="
  echo "gf180-sar-adc smoke test run: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "PDK_ROOT=$PDK_ROOT"
  echo "PDK=$PDK"
  echo "xschem: $(xschem --version 2>&1 | head -1)"
  echo "ngspice: $(ngspice -v 2>&1 | sed -n '2p')"
  echo "===================================================================="
} | tee -a "$LOG"

echo "-- xschem netlist --" | tee -a "$LOG"
xschem -n -x -q -r --rcfile "$RCFILE" -o "$OUT_DIR" "$SCH" 2>&1 | tee -a "$LOG"

if [[ ! -f "$NETLIST" ]]; then
  echo "ERROR: netlist not produced at $NETLIST" >&2
  exit 1
fi

echo "-- ngspice run --" | tee -a "$LOG"
(cd "$OUT_DIR" && ngspice -b "$(basename "$NETLIST")") 2>&1 | tee -a "$LOG"

echo "-- smoke test complete --" | tee -a "$LOG"
