#!/usr/bin/env python3
"""Produce a PDK-bound, parasitic-aware extraction of `adc_top`/`adc_block`
for post-layout resimulation -- issue #17's first deliverable ("parasitic
extraction of the final, DRC/LVS-clean layout").

This is a **second, additive** extraction of the same committed GDS
`layout/lvs/run_lvs.py` already extracts and LVS-matches -- it does not
replace that flow, and does not touch `layout/lvs/`'s manifests, reports or
records. The two extractions serve different purposes and are deliberately
NOT the same invocation:

  * `layout/lvs/run_lvs.py` runs `klt extract --deck gf180mcu` (bare
    `nfet`/`pfet` device classes, no parasitics, no PDK) because that is what
    `klt lvs`'s netlist comparer needs: a schematic-equivalent connectivity
    graph to diff against `design/`'s reference, not a simulatable circuit.
  * This script runs `klt extract --deck gf180mcu --pdk <variant> --pdk-root
    <root> --parasitics`, which additionally (a) binds every MOS device to
    the real PDK subcircuit (`nfet_03v3`/`pfet_03v3`), so the written SPICE
    is a drop-in `.include` against the same `sm141064.ngspice` library
    `design/`'s schematics simulate against, and (b) injects a first-order
    lumped R/C parasitic network per net. Neither flag exists on the LVS
    extraction, and turning them on there would break every `expect` in
    `layout/lvs/cells/cells.json` for no LVS benefit (the comparer never
    reads the injected R/C, and `--pdk` only changes SPICE serialization,
    not the JSON fields LVS asserts against).

Usage
-----
    python3 layout/adc-top/extract_parasitics.py            # extract + write
    python3 layout/adc-top/extract_parasitics.py --check    # extract, verify
                                                              # existing output
                                                              # is reproduced
                                                              # byte-for-byte,
                                                              # write nothing

Requires `klt` on PATH (`../toolchain.json`'s pin, checked via
`../toolchain_pin.py` before anything runs) and a resolvable gf180mcu PDK
install (`PDK_ROOT`/`PDK` env vars, or any other order `klt pdk find`
supports -- see `docs/environment-setup.md`). Neither the KLayout GUI
application nor a from-source `klayout` Python build is needed; the pip
`klayout` package `klt` itself depends on is enough, and no GDS is
regenerated by this script (it reads the committed `adc_top.gds`/
`adc_block.gds` `gen_adc_top.py` already produced and verified DRC/LVS-clean).

Known limitation this extraction does NOT resolve -- read before resimulating
------------------------------------------------------------------------------
Every PMOS device's body (Nwell) terminal in the written netlist lands on an
**anonymous, internal, non-pin net** (e.g. `$157`), not `vdd` the way
`design/adc-top/adc_top.spice`'s schematic ties it. This is a documented,
upstream limitation of the pinned `klt`'s curated gf180mcu extraction deck
(no distinct tap/well-label layer -- see `klt`'s own `docs/cli/extract.md`
"Coverage" section), not a bug in this script or in the drawn layout. Directly
instantiating the netlist this script writes and simulating it will converge,
but with every PMOS body floating to whatever its own source/drain diodes
settle to -- verified directly (a one-PMOS smoke test came back with the body
node at ~0 V against a driven-low source, not the 3.3 V the schematic ties it
to) -- not the physically-installed single-well bias. See `../README.md`
"Extracted-netlist resimulation: the open PMOS-body gap" for the full
writeup, the filed upstream friction issue
(2AMLogic/klayout-tools#555), and what closes this gap.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LAYOUT_DIR = os.path.abspath(os.path.join(HERE, os.pardir))
OUT_DIR = os.path.join(HERE, "parasitics")

if LAYOUT_DIR not in sys.path:
    sys.path.insert(0, LAYOUT_DIR)

import toolchain_pin  # noqa: E402  (import follows the sys.path setup above)

EXIT_OK = 0
EXIT_TOOLING = 1
EXIT_MISMATCH = 2

# Each entry: (gds file name, top cell name, output stem).
TARGETS = [
    ("adc_top.gds", "ADC_TOP", "adc_top"),
    ("adc_block.gds", "ADC_BLOCK", "adc_block"),
]


class ToolingError(Exception):
    """Something about the environment, not the layout, is wrong."""


def find_klt() -> str:
    klt = shutil.which("klt")
    if klt is None:
        raise ToolingError(
            "`klt` not found on PATH. Install klayout-tools "
            "(https://github.com/2AMLogic/klayout-tools), e.g.\n"
            "    uv tool install git+https://github.com/2AMLogic/klayout-tools"
        )
    return klt


def resolve_pdk(klt: str) -> dict:
    """Resolve the gf180mcu PDK install via `klt pdk find` -- the same
    resolver every other PDK-aware `klt` verb uses, so this script never
    hardcodes a PDK path and honors whatever `PDK_ROOT`/`PDK` (or other
    resolution order) the caller's environment already has set up for
    `sim/`'s own harness (`sim/harness/pdk.py`)."""
    proc = subprocess.run(
        [klt, "pdk", "find", "--format", "json"], capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise ToolingError(
            "`klt pdk find` could not resolve a gf180mcu PDK install "
            f"(exit {proc.returncode}): {proc.stderr}\n"
            "Set PDK_ROOT (and optionally PDK, default gf180mcuD) -- see "
            "docs/environment-setup.md."
        )
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise ToolingError(f"`klt pdk find` emitted non-JSON: {exc}") from exc


def run_extract(klt: str, pdk: dict, gds_name: str, top: str, stem: str) -> dict:
    gds_path = os.path.join(HERE, gds_name)
    if not os.path.isfile(gds_path):
        raise ToolingError(
            f"{gds_path} not found -- run "
            "`python3 layout/adc-top/gen_adc_top.py` first."
        )
    os.makedirs(OUT_DIR, exist_ok=True)
    out_spice = os.path.join(OUT_DIR, f"{stem}.parasitics.spice")
    out_json = os.path.join(OUT_DIR, f"{stem}.parasitics.json")
    cmd = [
        klt,
        "extract",
        gds_path,
        "--deck",
        "gf180mcu",
        "--top",
        top,
        "--pdk",
        pdk["variant"],
        "--pdk-root",
        pdk["root"],
        "--parasitics",
        "-o",
        out_spice,
        "--format",
        "json",
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise ToolingError(
            f"`klt extract` failed on {gds_name} (exit {proc.returncode}):\n"
            f"{proc.stderr}"
        )
    report = json.loads(proc.stdout)
    with open(out_json, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, sort_keys=True)
        fh.write("\n")
    return {"cmd": cmd, "report": report, "out_spice": out_spice, "out_json": out_json}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="extract and verify against the committed output, write nothing",
    )
    args = parser.parse_args()

    try:
        klt = find_klt()
        pin = toolchain_pin.load_toolchain_pin()
        problem = toolchain_pin.klt_capability_error(klt, pin)
        if problem:
            raise ToolingError(problem)
        pdk = resolve_pdk(klt)
    except ToolingError as exc:
        print(f"TOOLING ERROR: {exc}", file=sys.stderr)
        return EXIT_TOOLING

    print(f"klt: {klt}")
    print(f"pdk: {pdk['variant']} @ {pdk['root']} ({pdk['version']})")
    print()

    mismatches: list[str] = []
    for gds_name, top, stem in TARGETS:
        try:
            if args.check:
                out_spice = os.path.join(OUT_DIR, f"{stem}.parasitics.spice")
                if not os.path.isfile(out_spice):
                    mismatches.append(
                        f"{stem}: no committed output at {out_spice} -- run "
                        "without --check first"
                    )
                    continue
                before_spice = open(out_spice, encoding="utf-8").read()
                # Only the written SPICE circuit body is checked for
                # byte-reproducibility. The sibling `.json` report's
                # `file`/`netlist_path`/`pdk.root` fields are absolute paths
                # of the machine that ran the extraction (same precedent as
                # `layout/lvs/reports/`'s committed extract reports) and are
                # expected to differ run to run -- they record what was
                # literally invoked, not a portable artifact, so they are
                # deliberately NOT part of this reproducibility check.
                result = run_extract(klt, pdk, gds_name, top, stem)
                after_spice = open(result["out_spice"], encoding="utf-8").read()
                if before_spice != after_spice:
                    mismatches.append(
                        f"{stem}: extraction is not byte-reproducible "
                        "(committed output does not match a fresh run)"
                    )
            else:
                result = run_extract(klt, pdk, gds_name, top, stem)
        except ToolingError as exc:
            print(f"TOOLING ERROR ({stem}): {exc}", file=sys.stderr)
            return EXIT_TOOLING

        report = result["report"]
        print(
            f"{stem}: {report['device_count']} devices "
            f"({report['device_counts']}), {report['net_count']} nets, "
            f"parasitics: {report['parasitics']['r_count']} R/C pairs, "
            f"{report['parasitics']['total_capacitance_ff']:.1f} fF total -> "
            f"{result['out_spice']}"
        )

    if mismatches:
        print()
        for m in mismatches:
            print(f"MISMATCH: {m}", file=sys.stderr)
        return EXIT_MISMATCH

    print()
    print(
        "Known limitation (not fixed by this script): every PMOS body lands "
        "on an anonymous, un-biased net in the written netlist -- see this "
        "module's own docstring and ../README.md before resimulating."
    )
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
