// -----------------------------------------------------------------------
// sar_ctrl.v -- synchronous SAR control logic, RTL (issue #272)
//
// HAND-AUTHORED. Not machine-generated. This is the digital-flow source of
// truth for the gate-level netlist (DR-0010's "rung 3" sign-off path); the
// rung-1 ideal-XSPICE model (design/sar-logic/sar_ctrl.spice, generated by
// gen_sar_logic.py) remains the executable specification this file is
// checked against -- design/sar-logic/README.md Sec "Path to the netlist
// layout and LVS will use (#15)" is authoritative on that relationship.
//
// Behaviour implemented here (see design/sar-logic/README.md for the full
// narrative derivation) is fixed by ratified decision records; this file
// implements them, it does not choose them:
//
//   DR-0003  external clock, M = 16 -> 16 phases per conversion
//   DR-0005  10-bit parallel output register in scope, SPI deferred
//   DR-0008  synchronous SAR logic (one clock, rising edges only, no
//            gated/inverted clock anywhere)
//   DR-0009  no redundancy / plain binary weighting -- one decision
//            sequence per output code
//   DR-0011  MCS / Vcm switching, free MSB, 9 switched weights (256..1)
//            per side, mode-dependent side switching -- superseded by
//            DR-0014 on the sampling phase ONLY; everything else it
//            decided is re-ratified
//   DR-0014  BOTTOM-PLATE sampling: a fourth one-hot leg to V_in per cell,
//            one top-plate switch to V_cm per side, and a two-phase
//            sample in which the top-plate switch opens FIRST
//   DR-0023  gf180mcu_fd_sc_mcu7t5v0 / mcu9t5v0 standard cells at the
//            block's 3.3 V digital rail (this file is what gets synthesized
//            against them, design/sar-logic/flow/synth_sar_ctrl.py)
//
// Port list is the sar_ctrl_a subckt's, verbatim (design/sar-logic/
// sar_ctrl.spice, _ports_ctrl_analog() in gen_sar_logic.py): the same 71
// scalar nets in the same order, so a testbench built against sar_ctrl_a
// can swap this module (or its synthesized gate netlist) in unedited.
// sar_ctrl_a's own ports are already fully digital (clk/start/mode/cmp in;
// samp_tp_n/sel_in_n/drdy/c9..c0/the 54 switch-driver legs out) -- the
// SPICE subckt's adc_bridge/dac_bridge pairs are non-inverting analog<->
// digital level converters at the XSPICE boundary, an artifact of ngspice
// event-driven simulation that a synthesizable RTL module has no
// counterpart for and does not need one: every signal in this module IS a
// digital signal already.
//
// Single FLAT module, deliberately -- no submodule instantiation, no
// generate-block register arrays. Two reasons:
//   1. `klt equiv`'s "yosys-sequential" engine (register-correspondence
//      equivalence, Yosys's equiv_make/equiv_induct family) pairs gold/gate
//      registers BY NAME. A flat module free of hierarchy or synthesizer-
//      introduced dotted/bit-blasted names keeps every register name
//      (ph0..ph15, eng9..eng1, q9..q0, c9..c0) identical before and after
//      `klt synthesize`'s `synth`/`dfflibmap`/`abc` passes, which is what
//      makes that pairing possible at all.
//   2. It mirrors the ideal model's own choice not to build sar_ctrl_a out
//      of deeply nested subckts beyond sar_bitreg/sar_slice/sar_seq -- this
//      file inlines those three at the signal-equation level instead of as
//      Verilog submodules, for the same reason.
//
// Naming below deliberately tracks gen_sar_logic.py's own internal names
// (ph<k>, eng<bit>, q<bit>, dec, smpb, arm<bit>) rather than re-deriving
// fresh names, so a reader comparing this file against the generator's
// `library()` function (and against design/sar-logic/README.md's narrative)
// is reading the same design twice under the same vocabulary, not two
// designs that happen to agree.
// -----------------------------------------------------------------------

`timescale 1ns / 1ps

module sar_ctrl_a (
    input  wire clk,
    input  wire start,
    input  wire mode,
    input  wire cmp,
    output wire samp_tp_n,
    output wire sel_in_n,
    output wire drdy,
    output wire c9,
    output wire c8,
    output wire c7,
    output wire c6,
    output wire c5,
    output wire c4,
    output wire c3,
    output wire c2,
    output wire c1,
    output wire c0,
    // p side (side "p" of every weight, 256 down to 1)
    output wire rel_n_256p,
    output wire sel_hi_n_256p,
    output wire sel_lo_n_256p,
    output wire rel_n_128p,
    output wire sel_hi_n_128p,
    output wire sel_lo_n_128p,
    output wire rel_n_64p,
    output wire sel_hi_n_64p,
    output wire sel_lo_n_64p,
    output wire rel_n_32p,
    output wire sel_hi_n_32p,
    output wire sel_lo_n_32p,
    output wire rel_n_16p,
    output wire sel_hi_n_16p,
    output wire sel_lo_n_16p,
    output wire rel_n_8p,
    output wire sel_hi_n_8p,
    output wire sel_lo_n_8p,
    output wire rel_n_4p,
    output wire sel_hi_n_4p,
    output wire sel_lo_n_4p,
    output wire rel_n_2p,
    output wire sel_hi_n_2p,
    output wire sel_lo_n_2p,
    output wire rel_n_1p,
    output wire sel_hi_n_1p,
    output wire sel_lo_n_1p,
    // n side (side "n" of every weight, 256 down to 1)
    output wire rel_n_256n,
    output wire sel_hi_n_256n,
    output wire sel_lo_n_256n,
    output wire rel_n_128n,
    output wire sel_hi_n_128n,
    output wire sel_lo_n_128n,
    output wire rel_n_64n,
    output wire sel_hi_n_64n,
    output wire sel_lo_n_64n,
    output wire rel_n_32n,
    output wire sel_hi_n_32n,
    output wire sel_lo_n_32n,
    output wire rel_n_16n,
    output wire sel_hi_n_16n,
    output wire sel_lo_n_16n,
    output wire rel_n_8n,
    output wire sel_hi_n_8n,
    output wire sel_lo_n_8n,
    output wire rel_n_4n,
    output wire sel_hi_n_4n,
    output wire sel_lo_n_4n,
    output wire rel_n_2n,
    output wire sel_hi_n_2n,
    output wire sel_lo_n_2n,
    output wire rel_n_1n,
    output wire sel_hi_n_1n,
    output wire sel_lo_n_1n
);

  // ---------------------------------------------------------------------
  // 16-phase one-hot sequencer (sar_seq). A one-hot ring; `start` is a
  // SYNCHRONOUS restart that forces stage 0 and clears every other stage
  // on the same edge, so an asserted `start` cannot inject a second token
  // alongside a circulating one. Real hardware has no XSPICE `ic=1`
  // initial condition: assert `start` for >= 1 clock after power-up to
  // seed the ring (ph0=1, every other phase 0) before relying on any
  // other output of this module -- see design/sar-logic/rtl/README.md.
  // ---------------------------------------------------------------------
  reg [15:0] ph;

  always @(posedge clk) begin
    ph[0] <= start | ph[15];
    ph[1] <= ph[0] & ~start;
    ph[2] <= ph[1] & ~start;
    ph[3] <= ph[2] & ~start;
    ph[4] <= ph[3] & ~start;
    ph[5] <= ph[4] & ~start;
    ph[6] <= ph[5] & ~start;
    ph[7] <= ph[6] & ~start;
    ph[8] <= ph[7] & ~start;
    ph[9] <= ph[8] & ~start;
    ph[10] <= ph[9] & ~start;
    ph[11] <= ph[10] & ~start;
    ph[12] <= ph[11] & ~start;
    ph[13] <= ph[12] & ~start;
    ph[14] <= ph[13] & ~start;
    ph[15] <= ph[14] & ~start;
  end

  // ---------------------------------------------------------------------
  // DR-0014's two-phase bottom-plate sample, laid inside the same 4-clock
  // sample window (ph0..ph3): `samp_tp_n` (top-plate Vcm switch) covers
  // ph0..ph2 only and its falling edge (ph2->ph3) is the sampling instant;
  // `sel_in_n` (every cell's fourth, V_in, leg -- one broadcast net for
  // both sides) covers the full ph0..ph3 window, so the bottom plates
  // leave V_in one whole clock AFTER the top plate has already floated.
  // ---------------------------------------------------------------------
  assign samp_tp_n = ph[0] | ph[1] | ph[2];
  assign sel_in_n = ph[0] | ph[1] | ph[2] | ph[3];
  wire smpb = ~sel_in_n;

  // Comparator decision in OUTPUT-BIT polarity. Bottom-plate sampling
  // inverts the residue with respect to the input (DR-0014): after the
  // sample, top_p - top_n = -k*(V_inp - V_inn), so the controller inverts
  // the comparator ONCE at its own boundary. `dec` = 1 means "the sampled
  // input is above the DAC's current estimate, add this weight".
  wire dec = ~cmp;

  // `drdy`: asserted ph15, the last phase of the conversion.
  assign drdy = ph[15];

  // endconv: the edge leaving the last bit trial (ph13) releases every
  // slice's engage flag back to 0 for the next sample phase.
  wire endconv = ph[13];

  // ---------------------------------------------------------------------
  // Nine bit slices (sar_slice), weights 256 down to 1, MSB-first. Each
  // slice's own `arm` phase is the trial BEFORE its own: the slice's `eng`
  // flag turns on entering its own trial, and its `dir`/`q<bit>` register
  // captures, on that SAME edge, the decision made during the PRECEDING
  // trial (free-MSB for weight 256's slice) -- which is simultaneously
  // (a) that preceding trial's own output bit, and (b) the switch
  // direction this slice drives for its own, now-starting, trial. That
  // double duty is the SAR recursion itself, not an aliasing bug -- see
  // design/sar-logic/README.md "Switch decode" and gen_sar_logic.py's
  // sar_slice docstring.
  //
  //   weight | bit | arm    | output bit register
  //   -------|-----|--------|---------------------
  //   256    | 9   | ph[4]  | q9  (captures the free-MSB decision, ph4)
  //   128    | 8   | ph[5]  | q8  (captures weight-256 trial's decision)
  //   64     | 7   | ph[6]  | q7
  //   32     | 6   | ph[7]  | q6
  //   16     | 5   | ph[8]  | q5
  //   8      | 4   | ph[9]  | q4
  //   4      | 3   | ph[10] | q3
  //   2      | 2   | ph[11] | q2
  //   1      | 1   | ph[12] | q1  (captures weight-2 trial's decision;
  //                                 ALSO drives weight-1's own switches)
  // ---------------------------------------------------------------------
  reg eng9, eng8, eng7, eng6, eng5, eng4, eng3, eng2, eng1;
  reg q9, q8, q7, q6, q5, q4, q3, q2, q1;

  wire arm9 = ph[4];
  wire arm8 = ph[5];
  wire arm7 = ph[6];
  wire arm6 = ph[7];
  wire arm5 = ph[8];
  wire arm4 = ph[9];
  wire arm3 = ph[10];
  wire arm2 = ph[11];
  wire arm1 = ph[12];

  always @(posedge clk) begin
    if (arm9) q9 <= dec;
    eng9 <= (arm9 | eng9) & ~endconv;

    if (arm8) q8 <= dec;
    eng8 <= (arm8 | eng8) & ~endconv;

    if (arm7) q7 <= dec;
    eng7 <= (arm7 | eng7) & ~endconv;

    if (arm6) q6 <= dec;
    eng6 <= (arm6 | eng6) & ~endconv;

    if (arm5) q5 <= dec;
    eng5 <= (arm5 | eng5) & ~endconv;

    if (arm4) q4 <= dec;
    eng4 <= (arm4 | eng4) & ~endconv;

    if (arm3) q3 <= dec;
    eng3 <= (arm3 | eng3) & ~endconv;

    if (arm2) q2 <= dec;
    eng2 <= (arm2 | eng2) & ~endconv;

    if (arm1) q1 <= dec;
    eng1 <= (arm1 | eng1) & ~endconv;
  end

  // bit0 (LSB): weight-1's OWN decision, captured directly (no slice of
  // its own array cell drives it -- weight 1's cell switches off q1, per
  // the table above) at the edge leaving ph13, the trial weight-1 itself
  // is exercised in (sar_bitreg with en = ph13, d = dec; xb0 in the
  // generator).
  reg q0;
  always @(posedge clk) begin
    if (ph[13]) q0 <= dec;
  end

  // Switch decode per weight w and side s, combinational, FOUR one-hot
  // legs per cell (in = sel_in_n, shared; rel = !eng & !smp; p-side
  // hi = eng & dir, lo = eng & !dir; n-side hi = eng & !dir, lo = eng & dir,
  // n side additionally gated by `mode` -- differential only, DR-0011).
  //   rel_n_<w><s>     -> release to Vcm
  //   sel_hi_n_<w><s>  -> engage to V_REF
  //   sel_lo_n_<w><s>  -> engage to GND
  assign rel_n_256p = ~eng9 & smpb;
  assign sel_hi_n_256p = eng9 & q9;
  assign sel_lo_n_256p = eng9 & ~q9;
  assign rel_n_256n = (~eng9 | ~mode) & smpb;
  assign sel_hi_n_256n = (eng9 & mode) & ~q9;
  assign sel_lo_n_256n = (eng9 & mode) & q9;

  assign rel_n_128p = ~eng8 & smpb;
  assign sel_hi_n_128p = eng8 & q8;
  assign sel_lo_n_128p = eng8 & ~q8;
  assign rel_n_128n = (~eng8 | ~mode) & smpb;
  assign sel_hi_n_128n = (eng8 & mode) & ~q8;
  assign sel_lo_n_128n = (eng8 & mode) & q8;

  assign rel_n_64p = ~eng7 & smpb;
  assign sel_hi_n_64p = eng7 & q7;
  assign sel_lo_n_64p = eng7 & ~q7;
  assign rel_n_64n = (~eng7 | ~mode) & smpb;
  assign sel_hi_n_64n = (eng7 & mode) & ~q7;
  assign sel_lo_n_64n = (eng7 & mode) & q7;

  assign rel_n_32p = ~eng6 & smpb;
  assign sel_hi_n_32p = eng6 & q6;
  assign sel_lo_n_32p = eng6 & ~q6;
  assign rel_n_32n = (~eng6 | ~mode) & smpb;
  assign sel_hi_n_32n = (eng6 & mode) & ~q6;
  assign sel_lo_n_32n = (eng6 & mode) & q6;

  assign rel_n_16p = ~eng5 & smpb;
  assign sel_hi_n_16p = eng5 & q5;
  assign sel_lo_n_16p = eng5 & ~q5;
  assign rel_n_16n = (~eng5 | ~mode) & smpb;
  assign sel_hi_n_16n = (eng5 & mode) & ~q5;
  assign sel_lo_n_16n = (eng5 & mode) & q5;

  assign rel_n_8p = ~eng4 & smpb;
  assign sel_hi_n_8p = eng4 & q4;
  assign sel_lo_n_8p = eng4 & ~q4;
  assign rel_n_8n = (~eng4 | ~mode) & smpb;
  assign sel_hi_n_8n = (eng4 & mode) & ~q4;
  assign sel_lo_n_8n = (eng4 & mode) & q4;

  assign rel_n_4p = ~eng3 & smpb;
  assign sel_hi_n_4p = eng3 & q3;
  assign sel_lo_n_4p = eng3 & ~q3;
  assign rel_n_4n = (~eng3 | ~mode) & smpb;
  assign sel_hi_n_4n = (eng3 & mode) & ~q3;
  assign sel_lo_n_4n = (eng3 & mode) & q3;

  assign rel_n_2p = ~eng2 & smpb;
  assign sel_hi_n_2p = eng2 & q2;
  assign sel_lo_n_2p = eng2 & ~q2;
  assign rel_n_2n = (~eng2 | ~mode) & smpb;
  assign sel_hi_n_2n = (eng2 & mode) & ~q2;
  assign sel_lo_n_2n = (eng2 & mode) & q2;

  assign rel_n_1p = ~eng1 & smpb;
  assign sel_hi_n_1p = eng1 & q1;
  assign sel_lo_n_1p = eng1 & ~q1;
  assign rel_n_1n = (~eng1 | ~mode) & smpb;
  assign sel_hi_n_1n = (eng1 & mode) & ~q1;
  assign sel_lo_n_1n = (eng1 & mode) & q1;

  // ---------------------------------------------------------------------
  // 10-bit parallel output register (DR-0005: in scope, SPI deferred).
  // Loads {q9..q0} on the edge leaving ph14 (visible from ph15, the same
  // phase drdy asserts on).
  // ---------------------------------------------------------------------
  reg c9_r, c8_r, c7_r, c6_r, c5_r, c4_r, c3_r, c2_r, c1_r, c0_r;
  always @(posedge clk) begin
    if (ph[14]) begin
      c9_r <= q9;
      c8_r <= q8;
      c7_r <= q7;
      c6_r <= q6;
      c5_r <= q5;
      c4_r <= q4;
      c3_r <= q3;
      c2_r <= q2;
      c1_r <= q1;
      c0_r <= q0;
    end
  end

  assign c9 = c9_r;
  assign c8 = c8_r;
  assign c7 = c7_r;
  assign c6 = c6_r;
  assign c5 = c5_r;
  assign c4 = c4_r;
  assign c3 = c3_r;
  assign c2 = c2_r;
  assign c1 = c1_r;
  assign c0 = c0_r;

endmodule
